import {Simulation} from '../src/simulation';
import {LEVELS,levelForMode} from '../content/levels';
import {HERO_KEYS,HEROES,ENEMIES,TOWERS} from '../content/definitions';
import {distance} from '../src/math';
import type {HeroKind,TowerKind,GameMode,Difficulty} from '../src/types';
export function play(index:number,hero:HeroKind,upgrades:Record<string,number>={},variant=0,mode:GameMode='campaign',difficulty:Difficulty='normal',seed=9451,branchOverride?:0|1){
 const sim=new Simulation(levelForMode(LEVELS[index],mode),hero,difficulty,upgrades,seed),level=sim.level;
 const activePaths=new Set(level.waves.slice(0,2).flatMap(w=>w.groups.map(g=>g.path)));for(const path of [...activePaths]){let p=sim.connectedPath(path);const seen=new Set<number>();while(p!==undefined&&!seen.has(p)){seen.add(p);activePaths.add(p);p=sim.connectedPath(p);}}
 const coverage=(slot:number)=>sim.roads.reduce((sum,r)=>{let n=0;for(let d=r.total*.15;d<r.total*.93;d+=35)if(distance(level.slots[slot],r.at(d))<310&&!level.portals?.some(p=>sim.roads[p.path]===r&&d/r.total>p.from&&d/r.total<p.to))n+=(1+(d/r.total)*.4)*(activePaths.has(sim.roads.indexOf(r))?4:1);return sum+n;},0);
 const order=level.slots.map((_,i)=>i).sort((a,b)=>coverage(b)-coverage(a));
 const alternatives:TowerKind[][]=[['archer','archer','mage','barracks','engineer'],['mage','mage','barracks','archer','engineer'],['mage','mage','archer','barracks','engineer'],['engineer','mage','archer','barracks','mage'],['archer','mage','engineer','archer','mage'],['engineer','archer','mage','engineer','archer'],['archer','archer','archer','mage','mage'],['mage','archer','mage','mage','engineer']];
 const desired=variant>=2?alternatives[variant-2]:index<3?['archer','archer','barracks','archer','mage','engineer']as TowerKind[]:['archer','mage','barracks','engineer','mage','archer']as TowerKind[];
 const filtered=desired.filter(k=>level.allowedTowers?.includes(k));const families=mode==='iron'?variant>=2&&filtered.length?filtered:variant%2?[...level.allowedTowers!].reverse():level.allowedTowers!:desired;
 const built=new Set<number>(sim.towers.map(t=>t.slot)),log:string[]=[];let actions=0;const leaks:unknown[]=[];
 const command=(c:Parameters<Simulation['command']>[0])=>{const ok=sim.command(c);if(ok){actions++;if(['build','upgrade','tower-skill'].includes(c.type))log.push(Math.round(sim.time)+' '+JSON.stringify(c));}return ok;};
 const purchase=()=>{const targetCount=Math.min(mode==='iron'&&families.length===1?6:index<3?4:3,order.length);if(sim.towers.length<targetCount){const slot=order.find(s=>!built.has(s))!,kind=families[sim.towers.length%families.length];if(command({type:'build',slot,kind})){built.add(slot);return;}}
  const candidates=sim.towers.filter(t=>t.level<sim.maxLevel(t.kind)&&(t.level<3||[0,1].some(b=>sim.branchOpen(t.kind,b)))).sort((a,b)=>(a.level+(a.kind==='barracks'?1.5:0))-(b.level+(b.kind==='barracks'?1.5:0))||(a.kind==='barracks'?1:0)-(b.kind==='barracks'?1:0));
  const t=candidates[0];if(t){const preferred=branchOverride??variant%2;const branch=sim.branchOpen(t.kind,preferred)?preferred:1-preferred;if(command({type:'upgrade',slot:t.slot,branch}))return;}
  if(!t)for(const tower of sim.towers.filter(t=>t.branch>=0))for(let skill=0;skill<TOWERS[tower.kind].branches[tower.branch].skills.length;skill++)if(tower.skills[skill]<1&&command({type:'tower-skill',slot:tower.slot,skill}))return;
  if(!t&&sim.towers.length<order.length){const slot=order.find(s=>!built.has(s))!,kind=families[sim.towers.length%families.length];if(command({type:'build',slot,kind})){built.add(slot);return;}}
  if(!t&&sim.towers.length>=Math.min(7,order.length))for(const tower of sim.towers.filter(t=>t.branch>=0))for(let skill=0;skill<TOWERS[tower.kind].branches[tower.branch].skills.length;skill++)if(command({type:'tower-skill',slot:tower.slot,skill}))return;
 };
 const snow=level.facilities?.find(f=>f.kind==='sasquatch');if(snow&&variant<6){command({type:'cast',skill:'meteor',point:snow});command({type:'facility',id:snow.id});}const sunray=level.facilities?.find(f=>f.kind==='sunray');if(sunray)command({type:'facility',id:sunray.id});for(let i=0;i<10;i++)purchase();const camp=sim.towers.find(t=>t.kind==='barracks');if(HEROES[hero].range<100*900/768&&!camp)command({type:'move-hero',point:sim.nearestRoad(level.slots[order[0]]).point});if(camp)command({type:'move-hero',point:hero==='healer'?{x:camp.rally.x+55,y:camp.rally.y-25}:camp.rally});command({type:'next-wave'});
 for(let tick=0;tick<90000&&sim.result==='playing';tick++){if(tick%30===0){if(sunray&&sim.wave>=5&&sim.facilityStates.get(sunray.id)!.rank<4)command({type:'facility',id:sunray.id});purchase();const enemies=sim.enemies.filter(e=>e.hp>0).sort((a,b)=>(sim.roads[a.path].total-a.distance)/ENEMIES[a.kind].speed-(sim.roads[b.path].total-b.distance)/ENEMIES[b.kind].speed),lead=enemies[0];
   if(lead){if(sunray)command({type:'facility',id:sunray.id,point:enemies.find(e=>ENEMIES[e.kind].behavior.boss)??lead});const dense=enemies.map(e=>({e,n:enemies.filter(n=>distance(n,e)<120).length+e.hp/350})).sort((a,b)=>b.n-a.n)[0];if(sim.cooldowns.meteor===0&&dense.n>=2)command({type:'cast',skill:'meteor',point:dense.e});if(sim.cooldowns.reinforce===0&&!ENEMIES[lead.kind].flying){const point=sim.roads[lead.path].at(lead.distance+30);command({type:'cast',skill:'reinforce',point});}const boss=enemies.find(e=>ENEMIES[e.kind].behavior.boss);if(boss)for(const tower of sim.towers.filter(t=>t.kind==='barracks'||sim.allies.some(a=>a.tower===t.slot&&a.kind==='elemental'))){const point=sim.roads[boss.path].at(boss.distance+30);if(distance(sim.level.slots[tower.slot],point)<sim.stats(tower).range-20&&distance(tower.rally,point)>40)command({type:'rally',slot:tower.slot,point});}if(boss&&sim.hero.hp>0&&(HEROES[hero].range<100*900/768?distance(sim.hero,boss)>140:distance(sim.hero,boss)<100||distance(sim.hero,boss)>230))command({type:'move-hero',point:sim.roads[boss.path].at(Math.min(sim.roads[boss.path].total-60,boss.distance+(HEROES[hero].range<100*900/768?65:175)))});else {const heroLead=HEROES[hero].range<100*900/768?enemies.find(e=>!ENEMIES[e.kind].flying):lead;if(heroLead&&sim.hero.hp>0&&heroLead.distance/sim.roads[heroLead.path].total>(HEROES[hero].range<100*900/768?.15:.65)&&distance(sim.hero,heroLead)>180&&!sim.hero.commanded)command({type:'move-hero',point:sim.roads[heroLead.path].at(Math.min(sim.roads[heroLead.path].total-60,heroLead.distance+35))});}}
   for(const t of sim.towers)if(t.sealAt||t.iceClicks)command({type:'unseal',slot:t.slot});for(const e of sim.enemies)if(e.sheep)command({type:'pop-sheep',id:e.id});
  }const beforeLives=sim.lives;sim.step();if(sim.lives!==beforeLives)leaks.push({time:sim.time,enemy:sim.events.filter(e=>e.type==='leak').at(-1)?.kind});}
 return {seed,metrics:sim.metrics,leaks,heroDamage:sim.heroDamage,level:level.id,hero,mode,variant,result:sim.result,lives:sim.lives,time:Math.round(sim.time),gold:sim.gold,kills:sim.kills,heroLevel:sim.hero.level,actions,wave:sim.wave,pending:sim.spawns.length,remaining:sim.enemies.map(e=>({kind:e.kind,hp:e.hp,path:e.path,distance:e.distance,total:sim.enemyRoad(e).total,x:e.x,y:e.y,blocked:sim.blocked.get(e.id)?.kind})),towers:sim.towers.map(t=>({slot:t.slot,kind:t.kind,level:t.level,branch:t.branch})),log};
}

