from pathlib import Path
p=Path('src/types.ts');s=p.read_text(encoding='utf8')
s=s.replace('EnemyState extends Point {','EnemyState extends Point { shieldHits?:number;spectralArmorUntil?:number;')
s=s.replace('AllyState extends Point {','AllyState extends Point { stunnedUntil?:number;courageRank?:number;dot?:{until:number;next:number;power:number;interval:number;nonlethal:boolean};')
s=s.replace('LevelDefinition {','LevelDefinition { pathStarts?:number[];exitPoints?:Point[];')
s=s.replace('TowerState {','TowerState { sealClicks?:number;')
p.write_text(s,encoding='utf8')
p=Path('src/simulation.ts');s=p.read_text(encoding='utf8')
s="import {queueEnemy,enemyDeath,updateNativeEnemy,nativeWaveEvents,updateNativeFacilities} from './reference-combat';\n"+s
s=s.replace('type PendingSpawn={','type PendingSpawn={progress?:number;bounty?:number;generation?:number;')
s=s.replace('  heroMines:', '  nativeState:Record<string,number>={};\n  heroMines:')
s=s.replace('this.roads.map(r=>r.nearest(p))','this.roads.map(r=>({...r.nearest(p),road:r}))')
s=s.replace("if(t.sealAt)t.sealAt=0;", "if(t.sealAt){t.sealClicks=Math.max(0,(t.sealClicks??1)-1);if(!t.sealClicks)t.sealAt=0;}")
s=s.replace("NATIVE['soldier_reinforcement_'+Math.min(4,this.upgrades.reinforce??0)]", "NATIVE[['re_farmer','re_farmer_well_fed','re_conscript','re_warrior','re_legionnaire','re_legionnaire_ranged'][Math.min(5,this.upgrades.reinforce??0)]]")
s=s.replace("let end=0;", "let end=0;nativeWaveEvents(this);")
s=s.replace("this.time+(w.originalInterval??end+w.rest)", "this.time+(this.level.waves[this.wave]?.originalInterval??end+w.rest)")
s=s.replace("const def=ENEMIES[e.kind];const armor=", "const def=ENEMIES[e.kind];if(e.shieldHits){e.shieldHits--;this.emit('impact',e,{kind:'shield'});return;}if(kind==='physical'&&def.behavior.dodge&&this.rng.next()<def.behavior.dodge){this.emit('skill',e,{kind:'dodge'});return;}const armor=")
s=s.replace("e.armor*(e.statuses", "((e.spectralArmorUntil??0)>this.time?Math.max(e.armor,.5):e.armor)*(e.statuses")
s=s.replace("e.deathPaid=true;this.gold", "e.deathPaid=true;enemyDeath(this,e);this.gold")
s=s.replace("this.updateAllies(dt);this.updateTowers", "this.updateAllies(dt);updateNativeFacilities(this,dt);this.updateTowers")
s=s.replace("if(a.expires&&this.time>=a.expires)", "if((a.stunnedUntil??0)>this.time){a.moving=false;continue;}if(a.expires&&this.time>=a.expires)")
s=s.replace("*(a.buffUntil>this.time?1.25:1)","+(a.buffUntil>this.time?2*(a.courageRank??1):0)")
s=s.replace("this.spawn(s.kind,s.path,0,false,s.subPath??0);", "const road=this.laneRoads[s.path]?.[s.subPath??0]??this.roads[s.path],e=this.spawn(s.kind,s.path,s.progress??road.lengths[s.node??this.level.pathStarts?.[s.path]??0]??0,false,s.subPath??0);if(s.bounty!==undefined)e.bounty=s.bounty;e.generation=s.generation??0;")
s=s.replace("if(e.distance>=this.enemyRoad(e).total){e.hp=0;", "const exit=this.level.exitPoints?.map(p=>this.enemyRoad(e).nearest(p)).sort((a,b)=>a.distance-b.distance)[0];if(e.distance>=(exit&&exit.distance<55*REFERENCE_SCALE&&!connection?exit.progress:this.enemyRoad(e).total)){e.hp=0;")
s=s.replace("e.specialCd-=dt;", "e.specialCd-=dt;updateNativeEnemy(this,e,dt);")
# Discard the old universal boss/summoning implementation for reference entities.
s=s.replace("if(!e.sheep&&e.specialCd<=0){", "if(!def.native&&!e.sheep&&e.specialCd<=0){")
s=s.replace("t.disabledUntil=this.time+5;t.sealAt=0", "t.disabledUntil=this.time+6;t.sealAt=0")
s=s.replace("if(def.behavior.boss||['ogre','yeti','magma'].includes(e.kind))for(const other of this.allies.filter(f=>f!==a&&f.hp>0&&distance(f,a!)<55))this.hitAlly(other,def.damage*.5);", "const attack=NATIVE[def.native??'']?.melee?.attacks?.[0];if(attack?.damage_radius)for(const other of this.allies.filter(f=>f!==a&&f.hp>0&&distance(f,a!)<attack.damage_radius*REFERENCE_SCALE))this.hitAlly(other,this.random(def.minDamage??def.damage,def.damage));if(attack?.damage_type===4096)this.hitAlly(a,99999);")
s=s.replace("range,interval:b?.interval??d.interval[i]", "range:range*((t.buffUntil??0)>this.time?1.2:1),interval:(b?.interval??d.interval[i])*((t.buffUntil??0)>this.time?.8:1)")
s=s.replace("radius=t.kind==='engineer'?85:undefined", "radius=t.kind==='engineer'?(t.branch===0?65:55)*REFERENCE_SCALE:undefined")
s=s.replace("this.targets(e,200,true)","this.targets(e,95*REFERENCE_SCALE,true)")
s=s.replace("10+10*t.skills[1]", "this.random(0,10)+10*t.skills[1]")
s=s.replace("this.finalBossStarted=true;this.spawn('boss');", "this.finalBossStarted=true;const p={x:200+518*REFERENCE_SCALE,y:900-677*REFERENCE_SCALE};this.spawn('boss',0,this.roads[0].nearest(p).progress);")
p.write_text(s,encoding='utf8')
p=Path('content/reference-levels.ts');s=p.read_text(encoding='utf8')
s="import pathMetadata from './reference/steam-24662480/path-metadata.json';\n"+s
s=s.replace('paths,subPaths,pathConnections:', 'paths,subPaths,pathStarts:pathMetadata[index].start.map(n=>n-1),exitPoints:pathMetadata[index].exits.map(referencePoint),pathConnections:')
# Link special camps to the existing facility interaction.
s=s.replace('const scripts=eligible', "const facilities=eligible.flatMap((e,i)=>{const kind=e.template.includes('elf')?'elves':e.template.includes('sasquash')?'sasquatch':e.template==='tower_sunray'?'sunray':undefined;if(!kind||!e.pos)return[];const p=referencePoint(e.pos),rally=referencePoint(e['tower.default_rally_pos']??e.pos);let path=0,progress=0,best=Infinity;for(let pi=0;pi<paths.length;pi++)for(let ni=0;ni<paths[pi].length;ni++){const d=Math.hypot(paths[pi][ni].x-rally.x,paths[pi][ni].y-rally.y);if(d<best){best=d;path=pi;progress=ni/(paths[pi].length-1);}}return[{id:'native-facility-'+i,kind:kind as 'elves'|'sasquatch'|'sunray',...p,path,progress,cost:kind==='sasquatch'?400:100}];});\n const scripts=eligible")
s=s.replace('facilities:[]','facilities')
p.write_text(s,encoding='utf8')
