import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
await mkdir('test-results/visual-v3',{recursive:true});
const browser=await chromium.launch({channel:process.env.QA_BROWSER||'chrome',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1600,height:900}}),errors=[],missing=[];
page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)missing.push(r.url());});
await page.goto('http://127.0.0.1:5188',{waitUntil:'networkidle'});await page.locator('[data-action="training-skip"]').click();await page.locator('.world-node').first().waitFor();assert.equal(await page.locator('.world-node').count(),12);await page.screenshot({path:'test-results/visual-v3/world.png'});
await page.locator('[data-action="upgrades"]').click();assert.equal(await page.locator('.upgrade-tree-v3 article').count(),6);assert.equal(await page.locator('.upgrade-tree-v3 article button').count(),30);await page.screenshot({path:'test-results/visual-v3/upgrades.png'});await page.locator('[data-action="close"]').click();
await page.locator('[data-action="start"]').click();
for(const [slot,kind]of [[0,'archer'],[2,'barracks'],[3,'mage']]){const p=await page.evaluate(i=>window.__NAILONG__.sim.level.slots[i],slot);await page.mouse.click(p.x,p.y);await page.locator(`[data-action="build"][data-kind="${kind}"]`).click();await page.locator('[data-action="close-tower"]').click();}
assert.equal(await page.evaluate(()=>window.__NAILONG__.sim.towers.length),3);
await page.evaluate(()=>{const a=window.__NAILONG__,t=a.sim.towerAt(0);t.iceClicks=5;t.disabledUntil=a.sim.time+15;});
const frozen=await page.evaluate(()=>window.__NAILONG__.sim.level.slots[0]);for(let i=0;i<4;i++)await page.mouse.click(frozen.x,frozen.y);assert.equal(await page.evaluate(()=>window.__NAILONG__.sim.towerAt(0).iceClicks),1);await page.mouse.click(frozen.x,frozen.y);assert.equal(await page.evaluate(()=>window.__NAILONG__.sim.towerAt(0).iceClicks),0);await page.locator('[data-action="close-tower"]').click();
await page.keyboard.press('h');await page.mouse.click(1210,710);await page.waitForTimeout(150);const foot=()=>page.evaluate(()=>{const a=window.__NAILONG__,r=a.scene.units.get(a.sim.hero.id);return{frame:r.body.frame.name,texture:r.body.texture.key};});const footA=await foot();await page.waitForTimeout(110);const footB=await foot();assert.ok(footA.texture.startsWith('heroes-walk-')&&footA.frame!==footB.frame);await page.keyboard.press('Escape');await page.locator('#next-wave').click();
await page.locator('[data-action="speed"]').click();await page.locator('[data-action="speed"]').click();assert.equal(await page.locator('#speed').textContent(),'3×');await page.locator('[data-action="auto-wave"]').click();assert.equal(await page.evaluate(()=>window.__NAILONG__.sim.autoWave),false);
await page.evaluate(()=>{const a=window.__NAILONG__;a.sim.spawn('mushroom',0,100);a.sim.spawn('orc',0,170);a.scene.syncUnits();});
const poses=()=>page.evaluate(()=>[...window.__NAILONG__.scene.units.values()].map(r=>({id:r.id,frame:r.body.frame.name,walk:r.body.rotation})));
const before=await poses();await page.waitForTimeout(220);const after=await poses();assert.ok(after.some(b=>before.some(a=>a.id===b.id&&a.frame!==b.frame)),'authored walk poses must change');await page.screenshot({path:'test-results/visual-v3/battle.png'});
await page.locator('[data-action="pause"]').first().click();const t=await page.evaluate(()=>window.__NAILONG__.sim.time);await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>window.__NAILONG__.sim.time),t);await page.locator('[data-action="quit"]').click();
await page.locator('[data-action="editor"]').click();await page.locator('[data-work="level-count"]').fill('4');await page.locator('[data-work="level-count"]').press('Tab');assert.equal(await page.locator('[data-work="level-index"] option').count(),4);
await page.locator('[data-work="level-index"]').selectOption('1');await page.locator('[data-work="name"]').fill('河谷测试');await page.locator('[data-work="name"]').press('Tab');
await page.locator('[data-action="work-group-add"]').click();const count=await page.locator('.wave-group').count();await page.locator('[data-group="0"][data-field="count"]').fill('12');await page.locator('[data-group="0"][data-field="count"]').press('Tab');assert.equal(await page.evaluate(()=>window.__NAILONG__.ui.editorLevel.waves[0].groups[0].count),12);
await page.screenshot({path:'test-results/visual-v3/editor.png'});
await page.locator('[data-action="editor-mode"][data-mode="slots"]').click();const slots=await page.evaluate(()=>window.__NAILONG__.ui.editorLevel.slots.length);await page.mouse.click(1100,300);assert.equal(await page.evaluate(()=>window.__NAILONG__.ui.editorLevel.slots.length),slots+1);await page.locator('[data-action="editor-undo"]').click();assert.equal(await page.evaluate(()=>window.__NAILONG__.ui.editorLevel.slots.length),slots);await page.locator('[data-action="editor-redo"]').click();assert.equal(await page.evaluate(()=>window.__NAILONG__.ui.editorLevel.slots.length),slots+1);
await page.locator('[data-action="editor-panel-toggle"]').click();await page.mouse.click(1460,590);assert.equal(await page.locator('.editor-v2').evaluate(e=>e.classList.contains('hidden')),true);await page.keyboard.press('Control+z');await page.locator('[data-action="editor-panel-toggle"]').click();
const downloading=page.waitForEvent('download');await page.locator('[data-action="editor-export"]').click();const download=await downloading;assert.ok(download.suggestedFilename().endsWith('.json'));await download.saveAs('test-results/custom-campaign.json');
await page.locator('[data-action="editor-play"]').click();assert.equal(await page.evaluate(()=>window.__NAILONG__.sim.level.name),'河谷测试');await page.locator('[data-action="pause"]').first().click();await page.locator('[data-action="quit"]').click();assert.equal(await page.locator('[data-work="name"]').inputValue(),'河谷测试');await page.waitForTimeout(600);
await page.reload({waitUntil:'networkidle'});await page.locator('[data-action="editor"]').click();await page.locator('[data-work="level-index"]').waitFor();assert.equal(await page.locator('[data-work="level-index"] option').count(),4);await page.locator('[data-work="level-index"]').selectOption('1');assert.equal(await page.locator('[data-work="name"]').inputValue(),'河谷测试');assert.equal(await page.locator('.wave-group').count(),count);
// A two-stage one-enemy fixture exercises real wins and custom campaign transitions.
await page.evaluate(()=>{const u=window.__NAILONG__.ui,c=u.customCampaign;c.levels=c.levels.slice(0,2).map((l,i)=>({...l,id:'smoke-'+i,name:'连续试玩 '+(i+1),paths:[[{x:80,y:450},{x:1540,y:450}]],slots:[{x:300,y:340}],heroStart:{x:350,y:450},gold:265,obstacles:[],facilities:[],portals:[],prebuilt:[],waves:[{rest:0,groups:[{type:'mushroom',count:1,path:0,interval:1,delay:0}]}]}));u.editorIndex=0;u.showEditor(c.levels[0]);});
await page.locator('[data-action="work-campaign-play"]').click();for(let i=0;i<2;i++){await page.mouse.click(300,340);await page.locator('[data-action="build"][data-kind="archer"]').click();await page.locator('[data-action="close-tower"]').click();await page.locator('#next-wave').click();await page.locator('.result-modal').waitFor();assert.equal(await page.evaluate(()=>window.__NAILONG__.sim.result),'won');await page.locator('.battle-report summary').click();assert.ok(await page.locator('.battle-report tbody tr').count()>0);if(i===0){await page.locator('[data-action="custom-next"]').click();assert.equal(await page.evaluate(()=>window.__NAILONG__.sim.level.id),'smoke-1');}}
await page.locator('[data-action="quit"]').click();await page.locator('[data-action="home"]').click();await page.locator('[data-action="art"]').click();assert.equal(await page.evaluate(()=>window.__NAILONG__.scene.artEntries.length),50);for(let i=0;i<4;i++){await page.evaluate(()=>{window.__NAILONG__.scene.artClock=3.3;});await page.waitForTimeout(120);await page.screenshot({path:'test-results/visual-v3/art-page-'+i+'.png'});await page.locator('[data-action="art-page"][data-delta="1"]').click();}
assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);await writeFile('test-results/expansion-browser-report.json',JSON.stringify({status:'passed',errors,missing,authoredPosesChanged:true,campaignNodes:12,upgradeNodes:30,editorAutosaveAfterReload:true,checks:['map','build','three speeds','auto wave','pause','real animation poses','campaign editing','visual enemy groups','undo redo','campaign export','trial return','IndexedDB reload','five-click ice thaw','vertical articulated hero walk','collapsed-panel editing','real custom campaign wins and next level','all 50 animation entries']},null,2));await browser.close();console.log('Expansion browser smoke passed.');


