from pathlib import Path
p=Path('src/simulation.ts');s=p.read_text(encoding='utf-8')
def replace(a,b):
 global s
 assert a in s,a[:120]
 s=s.replace(a,b)
replace('queueEnemy,enemyDeath,updateNativeEnemy','queueEnemy,enemyDeath,nativeAllyDeath,updateNativeEnemy')
replace('type PendingSpawn={progress?', 'type PendingSpawn={hp?:number;progress?')
replace("a.armor=.3;a.expires=Infinity;this.route(a,this.roads[f.path].at(f.progress*this.roads[f.path].total));}","a.armor=.3;a.expires=Infinity;this.route(a,this.roads[f.path].at(f.progress*this.roads[f.path].total));}for(const ev of level.scriptEvents??[])if(ev.template==='soldier_s6_imperial_guard'&&ev.point){const base=NATIVE[ev.template],a=this.createSoldier(undefined,0,ev.point);a.kind='ancestor';a.summon={template:ev.template,minDamage:10,damage:30,range:base.melee.range*REFERENCE_SCALE,speed:base.motion.max_speed*REFERENCE_SCALE,interval:base.melee.cooldown,damageKind:'physical'};a.hp=a.maxHp=base.health.hp_max*(difficulty==='casual'?1.2:1);a.armor=base.health.armor;a.commanded=false;a.destination={...ev.point};a.anchor={...ev.point};a.waypoints=[];}")
replace("const armor=((e.spectralArmorUntil??0)>this.time?Math.max(e.armor,.5):e.armor)","const armor=e.armor")
replace("const guard=a.kind==='shield'&&a.buffUntil>this.time?.45:1;a.hp-=damage*(1-a.armor)*guard", "const armor=Math.min(.95,a.armor+(a.buffUntil>this.time?.05*(a.courageRank??0):0));a.hp-=damage*(1-armor)")
replace('if(a.hp<=0){this.metrics.allyDeaths++','if(a.hp<=0){nativeAllyDeath(this,a);this.metrics.allyDeaths++')
replace(":a.kind==='elemental'?8:Infinity;",":a.kind==='elemental'?8:a.summon?.template==='soldier_s6_imperial_guard'?3:Infinity;")
replace("if(t.branch===0&&t.skills[0]&&t.skillCd<=0){for(const a of this.allies.filter(a=>a.tower===t.slot&&a.hp>0&&a.hp<a.maxHp)){const amount=this.random(40,60)*t.skills[0];a.hp=Math.min(a.maxHp,a.hp+amount);this.emit('heal',a,{amount:Math.round(amount)});}t.skillCd=10;}","")
replace("const p=t?this.level.slots[t.slot]:this.level.heroStart", "const p=t?this.level.slots[t.slot]:a.summon?.template==='soldier_s6_imperial_guard'?a.anchor:this.level.heroStart")
replace("let moving=distance(a,goal)>3;", "let moving=distance(a,goal)>3;")
replace("const damage=this.random(lo??h?.minDamage??1,max??h?.damage??3)+(a.buffUntil>this.time?2*(a.courageRank??1):0);", "const damage=this.random(lo??h?.minDamage??1,max??h?.damage??3)+(a.buffUntil>this.time?2*(a.courageRank??1):0)+(t?.kind==='barracks'&&t.branch===1?10*t.skills[1]:0);")
replace("a.transformedUntil&&a.kind==='ingvar'?1:","a.transformedUntil&&a.kind==='ingvar'?template.melee.attacks[2].cooldown:")
replace("(t?this.stats(t).interval:nativeAttack?.cooldown??h?.interval??1)","(t?(template?.melee?.cooldown??this.stats(t).interval):blockedEnemy?(template?.melee?.cooldown??nativeAttack?.cooldown??h?.interval??1):(nativeAttack?.cooldown??h?.interval??1))")
replace("if(a.kind==='bolin'&&!blockedEnemy)","if(a.kind==='ingvar'&&a.transformedUntil)for(const hitTime of template.melee.attacks[2].hit_times.slice(1))this.hits.push({at:this.time+hitTime,target:e.id,point:{...e},damage,kind:'physical',source:a.id});if(a.kind==='elora'&&!blockedEnemy)this.addStatus(e,this.rng.next()<.2?'freeze':'slow',2,.5,a.id);if(a.kind==='bolin'&&!blockedEnemy)")
replace("this.random(25,45)*t.skills[2],'true'","this.random(25,45)*t.skills[2],'physical'")
replace("this.area(a,45*REFERENCE_SCALE,this.random(25,45)*t.skills[2],'physical'", "this.area(a,40*REFERENCE_SCALE,this.random(10,30)+15*t.skills[2],'physical'")
replace("const regen=template?.regen;if(!moving", "if(t?.kind==='barracks'&&t.branch===0&&t.skills[0]&&a.specialCd<=0&&a.hp<a.maxHp*.7){const amount=this.random(40,60)*t.skills[0];a.hp=Math.min(a.maxHp,a.hp+amount);a.specialCd=10;this.emit('heal',a,{amount});}const regen=template?.regen;if(a.kind==='ingvar'&&a.transformedUntil)a.hp=Math.min(a.maxHp,a.hp+(regen?.health??0)/.5*dt);if(!moving")
replace("if(!e.sheep&&behavior.regeneration)","if(!def.native&&!e.sheep&&behavior.regeneration)")
replace("const stunned=e.statuses.some(s=>s.type==='stun'||s.type==='freeze')", "const stunned=e.statuses.some(s=>s.type==='stun'||s.type==='freeze')||(e.immobileUntil??0)>this.time")
replace("const counter=a.kind==='shield'&&a.buffUntil>this.time&&!e.sheep;this.hitAlly(a,e.sheep?0:this.random(def.minDamage??def.damage,def.damage));if(counter)this.damage(e,def.damage*.4+4*a.level,'true',a.id);", "const native=NATIVE[def.native??''],ranged=!!def.behavior.ranged&&!this.blocked.has(e.id),attack=ranged?native?.ranged?.attacks?.[0]:native?.melee?.attacks?.[0],bullet=NATIVE[attack?.bullet]?.bullet,lo=bullet?.damage_min??def.minDamage??def.damage,hi=bullet?.damage_max??def.damage;let incoming=this.random(lo,hi)*((e.rageUntil??0)>this.time?2:1)*((e.damageBuffUntil??0)>this.time?1.2:1);if(ranged)e.attackCd=attack?.cooldown??def.interval;const counter=a.kind==='shield'?heroSnapshot(a).hero.skills.block_counter:undefined;if(counter?.level&&this.rng.next()<counter.chance[counter.level-1]&&!e.sheep){const reflected=incoming*(.5+.5*counter.level);incoming*=incoming>(heroSnapshot(a).dodge?.counter_attack?.damage_threshold??50)?(heroSnapshot(a).dodge?.counter_attack?.damage_factor??.3333333333):0;this.damage(e,reflected,'physical',a.id);}this.hitAlly(a,e.sheep?0:incoming);")
replace("const attack=NATIVE[def.native??'']?.melee?.attacks?.[0];if(attack?.damage_radius)","if(attack?.damage_radius)")
replace("(e.kind==='boss'&&e.phase===1?1.08:1)","(e.kind==='boss'&&e.phase===1?1.5:1)*((e.flyingUntil??0)>this.time?NATIVE.mod_gulaemon_fly.fast.speed_factor:1)")
replace("if(s.bounty!==undefined)e.bounty=s.bounty;e.generation", "if(s.bounty!==undefined)e.bounty=s.bounty;if(s.hp!==undefined)e.hp=Math.min(e.maxHp,s.hp);e.generation")
p.write_text(s,encoding='utf-8')
