import fs from 'node:fs';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import ffmpeg from 'ffmpeg-static';
const source='art/source/audio',output='public/assets/audio';fs.mkdirSync(output,{recursive:true});
const manifest={},credits=[];
function convert(name,input,filter='loudnorm=I=-18:TP=-1.5:LRA=11',ext='ogg'){
 const file=name+'.'+ext;execFileSync(ffmpeg,['-hide_banner','-loglevel','error','-y','-i',input,'-af',filter,'-ar','44100',...(ext==='ogg'?['-c:a','libvorbis','-q:a','4']:['-c:a','pcm_s16le']),path.join(output,file)]);credits.push({file,source:input,processing:filter});return file;
}
for(const[name,file]of [['forest','forest.wav'],['dark','dark.ogg'],['boss','boss.wav']])manifest['music-'+name]=[convert('music-'+name,source+'/'+file)];
const picks={bow:['rpg/Audio/creak1.ogg','rpg/Audio/creak2.ogg','rpg/Audio/creak3.ogg'],impact:['impact/Audio/impactWood_light_000.ogg','impact/Audio/impactWood_light_001.ogg','impact/Audio/impactWood_light_002.ogg'],shield:['impact/Audio/impactPlate_heavy_000.ogg','impact/Audio/impactPlate_heavy_001.ogg','impact/Audio/impactPlate_heavy_002.ogg'],cannon:['impact/Audio/impactMetal_heavy_000.ogg','impact/Audio/impactMetal_heavy_001.ogg','impact/Audio/impactMetal_heavy_002.ogg'],explosion:['impact/Audio/impactPunch_heavy_000.ogg','impact/Audio/impactPunch_heavy_001.ogg','impact/Audio/impactPunch_heavy_002.ogg'],magic:['interface/Audio/glass_001.ogg','interface/Audio/glass_002.ogg','interface/Audio/glass_003.ogg'],'magic-hit':['interface/Audio/glitch_001.ogg','interface/Audio/glitch_002.ogg','interface/Audio/glitch_003.ogg'],lightning:['interface/Audio/glitch_003.ogg','interface/Audio/glitch_004.ogg','interface/Audio/glass_003.ogg'],heal:['interface/Audio/confirmation_001.ogg'],upgrade:['interface/Audio/confirmation_002.ogg'],wave:['interface/Audio/bong_001.ogg'],leak:['interface/Audio/error_001.ogg'],ui:['interface/Audio/click_001.ogg'],victory:['interface/Audio/confirmation_004.ogg'],defeat:['interface/Audio/error_008.ogg'],boss:['impact/Audio/impactPlate_heavy_004.ogg']};
for(const[key,files]of Object.entries(picks)){manifest[key]=files.map((file,i)=>convert(key+'-'+i,source+'/'+file,'loudnorm=I=-16:TP=-2:LRA=7'+(['magic','heal','lightning'].includes(key)?',aecho=0.8:0.5:55|95:0.22|0.1':''),'wav'));}
// Add original decaying blast layers to licensed impacts. No runtime synthesizer.
for(const key of ['cannon','explosion'])for(let i=0;i<3;i++){
 const input=source+'/'+picks[key][i],file=`${key}-${i}.wav`,duration=key==='cannon'?.55:.95;
 const filter=`[1:a]lowpass=f=${key==='cannon'?1100:2200},afade=t=out:st=0:d=${duration},volume=.65[n];[2:a]afade=t=out:st=0:d=${duration},volume=.85[b];[0:a][n][b]amix=inputs=3:duration=longest,loudnorm=I=-17:TP=-2:LRA=7[out]`;
 execFileSync(ffmpeg,['-hide_banner','-loglevel','error','-y','-i',input,'-f','lavfi','-i',`anoisesrc=color=brown:duration=${duration}:seed=${9451+i}`,'-f','lavfi','-i',`sine=frequency=${key==='cannon'?76+i*6:52+i*5}:duration=${duration}`,'-filter_complex',filter,'-map','[out]','-ar','44100',output+'/'+file]);
 credits.push({file,source:input,processing:filter,originalLayers:'seeded brown noise + decaying low-frequency blast'});
}
// A locally authored, seeded wind bed; no oscillating melody fallback.
const rate=22050,n=rate*12,b=Buffer.alloc(44+n*2);b.write('RIFF');b.writeUInt32LE(36+n*2,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(rate,24);b.writeUInt32LE(rate*2,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(n*2,40);let noise=0,seed=9451;for(let i=0;i<n;i++){seed=(seed*1664525+1013904223)>>>0;noise=noise*.975+((seed/2**32)*2-1)*.025;const fade=Math.min(1,i/rate,(n-i)/rate);b.writeInt16LE(Math.round(noise*5000*fade),44+i*2);}fs.writeFileSync(source+'/wind-authored.wav',b);manifest.ambient=[convert('ambient',source+'/wind-authored.wav','loudnorm=I=-26:TP=-3:LRA=7')];
fs.writeFileSync(output+'/manifest.json',JSON.stringify(manifest,null,2));fs.writeFileSync(source+'/production.json',JSON.stringify({license:'CC0; authored wind is project-original',sources:['https://kenney.nl/assets/rpg-audio','https://kenney.nl/assets/impact-sounds','https://kenney.nl/assets/interface-sounds','https://opengameart.org/content/once-upon-a-time-loop','https://opengameart.org/content/dark-place-loop','https://opengameart.org/content/determined-pursuit-epic-orchestra-loop'],credits},null,2));console.log('Prepared',Object.values(manifest).flat().length,'local audio files.');
