from pathlib import Path
p=Path('tests/campaign-v2.test.ts');s=p.read_text(encoding='utf-8').replace("import {legacyFixture}","import {NATIVE} from '../content/reference-gameplay';\nimport {legacyFixture}")
def test(name,body):
 global s
 lines=s.splitlines();i=next(i for i,line in enumerate(lines) if "it('"+name in line);lines[i]=body;s='\n'.join(lines)+'\n'
s=s.replace('expect(d.hp).toBe(200)','expect(d.hp).toBe(210)')
test('boss seals have'," it('native Veznan seals require three clicks and disable only after their warning',()=>{const s=new Simulation({...LEVELS[11],gold:10000});s.command({type:'build',slot:0,kind:'mage'});s.command({type:'build',slot:1,kind:'archer'});s.wave=9;s.waveActive=true;s.nativeState.vezSeal=0;s.step();const towers=s.towers.filter(t=>t.sealAt);expect(towers.length).toBeGreaterThan(0);const cleared=towers[0];for(let i=0;i<NATIVE.mod_veznan_tower.required_clicks;i++)s.command({type:'unseal',slot:cleared.slot});expect(cleared.sealAt).toBe(0);advance(s,NATIVE.mod_veznan_tower.click_time+.1);expect(cleared.disabledUntil).toBe(0);expect(towers.filter(t=>t!==cleared).every(t=>t.disabledUntil>s.time)).toBe(true);});")
test('summoners stop'," it('native necromancers pause while blocked and queue their staggered summons',()=>{const s=new Simulation(fixture()),e=s.spawn('necromancer',0,330);e.nativeCds={action0:0};s.blocked.set(e.id,s.hero);s.updateEnemies(STEP);expect(s.spawns).toHaveLength(0);s.blocked.clear();s.updateEnemies(STEP);expect(s.spawns).toHaveLength(5);s.hero.hp=0;advance(s,1);expect(s.enemies.filter(e=>['skeleton','skeletonknight'].includes(e.kind))).toHaveLength(5);});")
s=s.replace('advance(s,4);expect(distance(s.hero,{x:900,y:400}))','advance(s,8);expect(distance(s.hero,{x:900,y:400}))')
test('twelve levels'," it('26 stages keep native wave counts and defer challenge configurations',()=>{expect(LEVELS.map(l=>l.waves.length)).toEqual([7,7,11,13,15,17,16,18,19,19,19,15,20,20,20,15,15,16,16,15,16,15,15,15,15,15]);for(const l of LEVELS){expect(l.modes).toBeUndefined();expect(()=>levelForMode(l,'iron')).toThrow();}expect(Object.values(TOWERS).flatMap(t=>t.branches.flatMap(b=>b.skills))).toHaveLength(18);expect(Object.values(UPGRADE_TREES).every(t=>t.length===5)).toBe(true);});")
s=s.replace("expect(old.legacy?.scores.forest.stars).toBe(3)","expect(old.legacy).toBeUndefined()")
p.write_text(s,encoding='utf-8')
p=Path('tests/experience-v3.test.ts');s=p.read_text(encoding='utf-8')
test('v3 starts'," it('v4 clears old campaign and codex but preserves settings',()=>{expect(freshSave().discovered).toEqual([]);const save=validateSave({version:2,scores:{'main:stage-01:campaign':{stars:3,lives:20,hero:'shield',difficulty:'normal'}},upgrades:{archer:1},settings:{music:false}});expect(save.version).toBe(4);expect(save.discovered).toEqual([]);expect(save.scores).toEqual({});expect(save.upgrades).toEqual({});expect(save.settings.music).toBe(false);});")
test('summoned enemies'," it('queued native summons prevent clear after their summoner dies',()=>{const l=fixture();l.waves[0].groups=[{type:'necromancer',count:1,path:0,interval:1,delay:0}];const s=new Simulation(l);s.command({type:'next-wave'});s.step();const leader=s.enemies[0];leader.nativeCds={action0:0};s.updateEnemies(STEP);expect(s.spawns.length).toBeGreaterThan(0);s.damage(leader,99999,'true');advance(s,1);expect(s.enemies.some(e=>['skeleton','skeletonknight'].includes(e.kind))).toBe(true);expect(s.autoWaveAt).toBe(Infinity);});")
p.write_text(s,encoding='utf-8')
