import {ASSET_BASE} from './assets';
import {ACTION_SCALES} from '../content/action-scales';
import {TowerRig} from './tower-rig';
import { paintRoads } from './road-art';
import { CombatFX } from './combat-fx';
import Phaser from 'phaser';
import {isMobile} from './viewport';
import { ENEMIES, HEROES, TOWERS, HERO_KEYS, ENEMY_KEYS } from '../content/definitions';
import { Road, Random, distance } from './math';
import { Simulation, STEP } from './simulation';
import type { AllyState, EnemyState, Point, CombatEvent, HeroKind } from './types';
export interface SceneHooks {ready:(scene:BattleScene)=>void;tick:()=>void;click:(point:Point)=>void;event:(event:CombatEvent)=>void;loadError:(key:string)=>void}
import { UnitRig } from './unit-rig';
type Particle={image:Phaser.GameObjects.Image;end:number;start:number;from:Point;to:Point;kind:string;rotation:number};
export class BattleScene extends Phaser.Scene {
  sim?:Simulation;paused=false;speed=1;selectedSlot=-1;heroSelected=false;inspectedUnitId?:number;mode:string='';lowQuality=false;
  background!:Phaser.GameObjects.Image;roadImage?:Phaser.GameObjects.Image;slots=new Map<number,Phaser.GameObjects.Container>();
  towers=new Map<number,TowerRig>();units=new Map<number,UnitRig>();range!:Phaser.GameObjects.Graphics;fx!:Phaser.GameObjects.Graphics;decor!:Phaser.GameObjects.Graphics;shadows!:Phaser.GameObjects.Graphics;healthBars!:Phaser.GameObjects.Graphics;
  combatFx!:CombatFX;lessonTarget?:string;
  particles:Particle[]=[];particlePool:Phaser.GameObjects.Image[]=[];texts:Phaser.GameObjects.Text[]=[];seen=0;accumulator=0;wall=0;hudTimer=0;gate?:Phaser.GameObjects.Image;
  editorActive=false;artMode=false;artClock=0;artPage=0;
  artEntries=[...HERO_KEYS.map(k=>({name:HEROES[k].name,sheet:'heroes',row:HEROES[k].row,kind:k,columns:8,size:115})),...['基础卫兵','升级守卫','皇家盾卫','狂战奶龙'].map((name,row)=>({name,sheet:'soldiers',row,kind:'soldier',columns:8,size:105})),...['精灵奶龙','雪人奶龙','大地奶龙'].map((name,row)=>({name,sheet:'special-allies',row,kind:['elf','sasquatch','elemental'][row],columns:8,size:115})),...ENEMY_KEYS.map(k=>({name:ENEMIES[k].name,sheet:ENEMIES[k].sheet,row:ENEMIES[k].row,kind:k,columns:7,size:ENEMIES[k].behavior.boss?140:105})),{name:'荆棘魔王 · 真身',sheet:'enemy-new-4',row:3,kind:'boss',columns:7,size:145}];
  previousPositions=new Map<number,Point>();
  renderedPoint(unit:AllyState|EnemyState){const prev=this.previousPositions.get(unit.id);if(!prev||this.paused)return unit;const alpha=this.accumulator/STEP;return{x:prev.x+(unit.x-prev.x)*alpha,y:prev.y+(unit.y-prev.y)*alpha};}
  constructor(public hooks:SceneHooks){super('battle');}
  preload(){for(const map of ['forest','river','ruins','home-v4.1','campaign-v2','campaign-v4','road-texture',...Array.from({length:26},(_,i)=>'map-'+String(i+1).padStart(2,'0'))])this.load.image(map,`${ASSET_BASE}${map}.webp`);for(const sheet of ['tower-plates','tower-operators','heroes-actions','soldiers-actions','heroes-walk-a','heroes-walk-b','soldiers-walk-a','soldiers-walk-b','heroes','soldiers','towers','enemies-a','enemies-b','enemy-new-1','enemy-new-2','enemy-new-3','enemy-new-4','special-allies'])this.load.spritesheet(sheet,`${ASSET_BASE}${sheet}.png`,{frameWidth:192,frameHeight:192});this.load.on('loaderror',(file:Phaser.Loader.File)=>this.hooks.loadError(file.key));}
  create(){this.background=this.add.image(800,450,'forest').setDisplaySize(1600,900).setDepth(0);
    for(const [sheet,cols,rows]of [['heroes',8,4],['soldiers',8,4],['enemies-a',7,5],['enemies-b',7,6],['enemy-new-1',7,8],['enemy-new-2',7,8],['enemy-new-3',7,8],['enemy-new-4',7,8],['special-allies',8,3]] as const){const tex=this.textures.get(sheet);for(let i=0;i<cols*rows;i++){const f=tex.get(i);tex.add(`${i}-body`,0,f.cutX,f.cutY,192,160);tex.add(`${i}-legL`,0,f.cutX,f.cutY+154,96,38);tex.add(`${i}-legR`,0,f.cutX+96,f.cutY+154,96,38);for(const n of [2,4,6])for(let j=0;j<n;j++)tex.add(`${i}-foot${n}-${j}`,0,f.cutX+j*192/n,f.cutY+(n===6?140:154),192/n,n===6?52:38);tex.add(`${i}-flight-body`,0,f.cutX+64,f.cutY,64,192);tex.add(`${i}-wing0`,0,f.cutX,f.cutY,72,192);tex.add(`${i}-wing1`,0,f.cutX+120,f.cutY,72,192);}}
    const towerTexture=this.textures.get('tower-plates');for(let i=0;i<20;i++){const f=towerTexture.get(i),cut=[[97,78,69,80,72],[135,118,102,96,110],[142,108,88,74,82],[134,122,108,114,97]][Math.floor(i/5)][i%5];towerTexture.add(`${i}-front`,0,f.cutX,f.cutY+cut,192,192-cut);}
    const canvas=this.textures.createCanvas('spark',32,32)!;const ctx=canvas.context;const gradient=ctx.createRadialGradient(16,16,0,16,16,16);gradient.addColorStop(0,'#fff');gradient.addColorStop(.3,'#fff8c4');gradient.addColorStop(1,'#fff0');ctx.fillStyle=gradient;ctx.fillRect(0,0,32,32);canvas.refresh();
    this.range=this.add.graphics().setDepth(10);this.fx=this.add.graphics().setDepth(1800);this.combatFx=new CombatFX(this.fx);this.decor=this.add.graphics().setDepth(3);this.shadows=this.add.graphics().setDepth(25);this.healthBars=this.add.graphics().setDepth(1700);
    this.input.on('pointerdown',(p:Phaser.Input.Pointer)=>{if(!isMobile()||!this.sim||this.editorActive)this.hooks.click({x:p.x,y:p.y});});this.hooks.ready(this);
  }
  clearBattle(){for(const slot of this.slots.values())slot.destroy();this.slots.clear();for(const t of this.towers.values())t.destroy();this.towers.clear();for(const u of this.units.values())u.destroy();this.units.clear();this.roadImage?.destroy();this.gate?.destroy();for(const p of this.particles)p.image.setVisible(false);this.particlePool.push(...this.particles.map(p=>p.image));this.particles=[];for(const t of this.texts)t.destroy();this.texts=[];this.range.clear();this.combatFx.clear();this.decor.clear();this.shadows.clear();this.healthBars.clear();this.selectedSlot=-1;this.heroSelected=false;this.inspectedUnitId=undefined;this.mode='';this.lessonTarget=undefined;this.editorActive=false;this.artMode=false;this.accumulator=0;this.seen=0;this.previousPositions.clear();}
  showHome(map='forest'){this.clearBattle();this.sim=undefined;this.background.setTexture(map);this.paused=false;}
  start(sim:Simulation){this.clearBattle();this.sim=sim;this.paused=false;this.speed=1;this.background.setTexture(sim.level.map);if(!sim.level.referenceBuild)this.makeRoads(sim.roads,sim.level.map);
    sim.level.slots.forEach((p,i)=>{
      const root=this.add.container(p.x,p.y).setDepth(20),ring=this.add.ellipse(0,0,96,52,0x6c603e,.35).setStrokeStyle(3,0xf4dc9b,.8),base=this.add.ellipse(0,-2,82,44,0xc5b68b,.45);
      const cross=this.add.text(0,-6,'＋',{fontFamily:'Georgia',fontSize:'34px',color:'#fff2bc',stroke:'#635b35',strokeThickness:3}).setOrigin(.5);
      root.add([ring,base,cross]);this.slots.set(i,root);
    });
    const exit=sim.level.exitPoints?.[0]??sim.roads[0].at(sim.roads[0].total);this.gate=this.add.image(Math.min(1530,exit.x),exit.y,'towers',8).setDisplaySize(155,155).setOrigin(.5,.85).setDepth(525);
    for(const f of sim.level.facilities??[]){const label=this.add.text(f.x,f.y-32,({elves:'精灵营地 100金',sasquatch:'冰封雪人 400金',sunray:'阳光神殿 100金',graveyard:'墓地',summon:'召唤阵',magma:'岩浆入口',guards:'王城守卫'}as const)[f.kind],{fontFamily:'Microsoft YaHei',fontSize:'17px',color:'#fff0b2',stroke:'#293830',strokeThickness:4}).setOrigin(.5).setDepth(1800);this.texts.push(label);const decoration=this.add.image(f.x,f.y,'towers',f.kind==='sunray'?13:f.kind==='elves'?0:f.kind==='sasquatch'?5:15).setOrigin(.5,.7).setDisplaySize(100,100).setDepth(f.y+40);this.slots.set(-100-this.slots.size,this.add.container(0,0,[decoration]));}
    this.addFloating({x:Math.min(1530,exit.x),y:exit.y},'守护出口',0xffefbc,3);
  }
  makeRoads(roads:Road[],map:string){this.roadImage?.destroy();this.roadImage=paintRoads(this,roads,map);}
  setArtMode(page=0){this.clearBattle();this.sim=undefined;this.artMode=true;this.artClock=0;this.artPage=page;this.background.setTexture('forest');this.artEntries.slice(page*16,page*16+16).forEach((entry,i)=>{const label=this.add.text(300+(i%4)*330,290+Math.floor(i/4)*180,entry.name,{fontFamily:'Microsoft YaHei',fontSize:'16px',color:'#fff2bf',stroke:'#243d29',strokeThickness:4}).setOrigin(.5).setDepth(1900);this.texts.push(label);});}
  syncUnits(){if(!this.sim)return;const alive=new Set<number>();for(const e of this.sim.enemies){alive.add(e.id);const d=ENEMIES[e.kind],rage=e.kind==='boss'&&e.phase===1,sheet=e.sheep?'enemy-new-4':rage?'enemy-new-4':d.sheet,row=e.sheep?7:rage?3:d.row;let rig=this.units.get(e.id);if(rig&&(rig.row!==row||rig.sheet!==sheet)){rig.destroy();this.units.delete(e.id);rig=undefined;}if(!rig){rig=new UnitRig(this,sheet,row,e.sheep?60:rage?215:e.phase===-1?d.size*.65:d.size,7,e.id);this.units.set(e.id,rig);}rig.draw(e,this.sim.time);}
    for(const a of this.sim.allies){alive.add(a.id);let row=a.kind in HEROES?HEROES[a.kind as HeroKind].row:0;let sheet=a.kind in HEROES?'heroes':a.kind==='soldier'?'soldiers':'special-allies';if(a.kind==='elf')row=0;if(a.kind==='sasquatch')row=1;if(a.kind==='elemental')row=2;if(a.kind==='soldier'&&a.tower!==undefined){const t=this.sim.towerAt(a.tower);row=t?.branch===1?3:t?.branch===0?2:(t?.level??1)>1?1:0;}let rig=this.units.get(a.id);if(rig&&rig.row!==row){rig.destroy();this.units.delete(a.id);rig=undefined;}if(!rig){rig=new UnitRig(this,sheet,row,a.kind==='soldier'?65:a.kind==='sasquatch'?130:110,sheet==='special-allies'?8:sheet==='enemy-new-4'?7:8,a.id);this.units.set(a.id,rig);}rig.draw(a,this.sim.time,a===this.sim.hero);}
    for(const [id,rig]of this.units)if(!alive.has(id)){rig.destroy();this.units.delete(id);}
    for(const unit of [...this.sim.enemies,...this.sim.allies]){const p=this.renderedPoint(unit);this.units.get(unit.id)?.root.setPosition(p.x,p.y).setDepth(Math.floor(100+p.y));}
    // Draw all shadows and health bars in shared batches, avoiding a graphics/sprite
    // pipeline switch for every individual actor in dense battles.
    this.shadows.clear();this.healthBars.clear();this.shadows.fillStyle(0x172518,.24);for(const tower of this.sim.towers){const p=this.sim.level.slots[tower.slot];this.shadows.fillEllipse(p.x,p.y+7,112,32,14);}
    for(const unit of [...this.sim.enemies,...this.sim.allies]){if(unit.hp<=0)continue;const rig=this.units.get(unit.id)!,p=this.renderedPoint(unit);this.shadows.fillEllipse(p.x,p.y,rig.size*.55,rig.size*.17,12);if(unit.hp<unit.maxHp||unit===this.sim.hero){const width=unit===this.sim.hero?60:38,y=p.y-rig.size*.86-(unit.kind==='bat'?15:0);this.healthBars.fillStyle(0x142820,.8).fillRect(p.x-width/2-2,y-2,width+4,8);this.healthBars.fillStyle(unit===this.sim.hero?0xffdd77:0x8fd277).fillRect(p.x-width/2,y,width*Math.max(0,unit.hp/unit.maxHp),4);}}
  }
  syncTowers(){if(!this.sim)return;for(const [slot,site]of this.slots){if(slot<0)continue;const t=this.sim.towerAt(slot);site.setVisible(!t);if(t){let rig=this.towers.get(slot);if(!rig){rig=new TowerRig(this,slot);this.towers.set(slot,rig);}rig.draw(t,this.sim);}else if(this.towers.has(slot)){this.towers.get(slot)!.destroy();this.towers.delete(slot);}}}
  addFloating(p:Point,text:string,color=0xffe2a4,duration=1.3){const obj=this.add.text(p.x,p.y-65,text,{fontFamily:'"Microsoft YaHei", sans-serif',fontSize:'20px',fontStyle:'bold',color:`#${color.toString(16).padStart(6,'0')}`,stroke:'#26382a',strokeThickness:4}).setOrigin(.5).setDepth(1900);this.texts.push(obj);this.tweens.add({targets:obj,y:obj.y-36,alpha:0,duration:duration*1000,onComplete:()=>{this.texts=this.texts.filter(t=>t!==obj);obj.destroy();}});}
  particle(from:Point,to:Point,kind:string,duration:number,color:number){const image=this.particlePool.pop()??this.add.image(0,0,'spark').setDepth(1600);image.setVisible(true).setTint(color).setAlpha(1).setScale(kind==='meteor'?1.2:.45);this.particles.push({image,from:{...from},to:{...to},kind,start:this.wall,end:this.wall+duration,rotation:0});}
  consumeEvents(){if(!this.sim)return;for(const e of this.sim.events){if(e.id<=this.seen)continue;this.seen=e.id;this.hooks.event(e);
    if(e.type==='teleport'){for(let i=0;i<8;i++)this.particle(e.point,{x:e.point.x+Math.cos(i)*40,y:e.point.y-60},'burst',.5,0xbbaaff);}if(e.type==='seal')this.addFloating(e.point,e.text??'点击解除封印',0xeeaaff,3);
    if(e.type==='spawn'&&e.kind&&ENEMIES[e.kind]?.behavior.boss){this.addFloating({x:800,y:170},ENEMIES[e.kind].name+'进入战场',0xffcc83,3);this.cameras.main.shake(240,.003);}
    if(['shot','impact','heal','skill'].includes(e.type))this.combatFx.add(e,this.wall);
    
    if(e.type==='heal')this.addFloating(e.point,`+${e.amount??''}`,0xc3ef98,.8);
    if(e.type==='upgrade')this.addFloating(e.point,e.text??'升级！',0xffe6a0);
    if(e.type==='death'){
      const enemy=e.kind&&e.kind in ENEMIES?ENEMIES[e.kind as keyof typeof ENEMIES]:undefined;
      if(enemy){const rage=e.kind==='boss'&&e.phase===1;const dead=this.add.image(e.point.x,e.point.y,e.morphed?'enemy-new-4':rage?'enemy-new-4':enemy.sheet,(e.morphed?7:rage?3:enemy.row)*7+6).setOrigin(.5,.84).setDisplaySize(e.morphed?60:rage?215:enemy.size,e.morphed?60:rage?215:enemy.size).setDepth(e.point.y+90);this.tweens.add({targets:dead,alpha:0,duration:950,onComplete:()=>dead.destroy()});if(enemy.behavior.boss){this.cameras.main.shake(320,.005);this.addFloating(e.point,'守护成功！',0xffe9ac,2);for(let i=0;i<12;i++)this.particle(e.point,{x:e.point.x+Math.cos(i)*95,y:e.point.y-35+Math.sin(i)*60},'burst',.8,0xffd484);}if(e.amount)this.addFloating(e.point,`+${e.amount}`,0xffd777,.8);}
      else {const special=['elf','sasquatch','elemental'].includes(e.kind??''),rig=e.actor!==undefined?this.units.get(e.actor):undefined,row=rig?.row??(special?['elf','sasquatch','elemental'].indexOf(e.kind!):e.kind&&e.kind in HEROES?HEROES[e.kind as HeroKind].row:0),sheet=special?'special-allies':e.kind==='soldier'?'soldiers':'heroes',size=e.kind==='soldier'?65:e.kind==='sasquatch'?130:100;const actionSheet=special?sheet:sheet+'-actions',factor=special?1:ACTION_SCALES[actionSheet]?.[row]??1;const dead=this.add.image(e.point.x,e.point.y,actionSheet,row*(special?8:6)+(special?6:5)).setDisplaySize(size*factor,size*factor).setOrigin(.5,176/192).setDepth(e.point.y+90);this.tweens.add({targets:dead,y:dead.y+3,alpha:0,duration:850,onComplete:()=>dead.destroy()});}

    }
    if(e.type==='warning'&&e.kind==='rage'){this.addFloating(e.point,'荆棘魔王显露真身！',0xffc477,2);for(let i=0;i<16;i++)this.particle(e.point,{x:e.point.x+Math.cos(i)*90,y:e.point.y+Math.sin(i)*65},'burst',.8,i%2?0xff7755:0x99cc66);}if(e.type==='warning'&&e.kind==='meteor')this.particle({x:e.point.x-200,y:e.point.y-500},e.point,'meteor',1.25,0xffbb55);
    if(e.type==='leak')this.addFloating({x:1490,y:450},`生命 -${e.amount}`,0xffada1);
    if(e.type==='skill'&&e.text)this.addFloating(e.point,e.text);
    if(e.type==='wave')this.addFloating({x:800,y:210},e.text??'',0xffefb6,2);
  }}
  drawRanges(){this.range.clear();if(!this.sim)return;for(const tower of this.sim.towers){const p=this.sim.level.slots[tower.slot],r=this.sim.stats(tower),target=this.sim.targets(p,r.range,r.air)[0],elapsed=this.sim.time-tower.firedAt,x=p.x+(target&&target.x<p.x?-24:24),y=p.y-(tower.level>=3?85:58);if(tower.kind==='mage'&&target&&tower.attackCd>0&&tower.attackCd<.25){const charge=1-tower.attackCd/.25;this.range.lineStyle(2,0xaadeff,.9).strokeCircle(x,y,5+charge*10);this.range.fillStyle(0xc5f4ff,.4).fillCircle(x,y,3+charge*5);}if(tower.kind==='engineer'&&elapsed>=0&&elapsed<.2){this.range.fillStyle(0xffd781,(1-elapsed/.2)*.9).fillCircle(x,y,12*(1-elapsed/.2));if(!this.lowQuality)for(let i=0;i<3;i++)this.range.fillStyle(0xbec7bb,(1-elapsed/.2)*.35).fillCircle(x+i*7,y-elapsed*40,5+i*3);}}const t=this.sim.towerAt(this.selectedSlot);if(this.selectedSlot>=0){const p=this.sim.level.slots[this.selectedSlot];const r=t?this.sim.stats(t).range:85;this.range.fillStyle(0xf5e3a7,.1).fillCircle(p.x,p.y,r);this.range.lineStyle(2,0xffe2a0,.8).strokeCircle(p.x,p.y,r);if(t?.kind==='barracks'){this.range.lineStyle(3,0x91e1e6,.8).strokeCircle(t.rally.x,t.rally.y,22);this.range.lineBetween(p.x,p.y,t.rally.x,t.rally.y);}}
    for(const e of this.sim.enemies){const p=this.renderedPoint(e);for(const status of e.statuses){const color={slow:0x8fe7ff,stun:0xffe582,poison:0x9fde64,burn:0xff974a,mark:0xcb99ff,root:0x92b14c,freeze:0xbbf3ff,curse:0xba82de}[status.type];this.range.lineStyle(2,color,.85).strokeEllipse(p.x,p.y,44,20);if(status.type==='stun'||status.type==='mark'){for(let i=0;i<3;i++){const a=this.sim.time*3+i*2.1;this.range.fillStyle(color,.9).fillCircle(p.x+Math.cos(a)*18,p.y-38+Math.sin(a)*5,3);}}else if(status.type==='burn'||status.type==='poison'){for(let i=0;i<3;i++)this.range.fillStyle(color,.6).fillCircle(p.x-14+i*14,p.y-12-(this.sim.time*20+i*7)%24,3);}}if(e.kind==='boss'&&e.phase===1)this.range.lineStyle(4,0xff7651,.7+.2*Math.sin(this.sim.time*5)).strokeEllipse(p.x,p.y,105,45);}
    if(this.inspectedUnitId!==undefined){const u=[...this.sim.enemies,...this.sim.allies].find(u=>u.id===this.inspectedUnitId&&u.hp>0);if(u){const p=this.renderedPoint(u);this.range.lineStyle(2,0xffe39c,.95).strokeEllipse(p.x,p.y,56,25);}}
    if(this.heroSelected){this.range.lineStyle(3,0xffe69c,.95).strokeEllipse(this.sim.hero.x,this.sim.hero.y,65,32);this.range.fillStyle(0xffe69c,.25).fillEllipse(this.sim.hero.destination.x,this.sim.hero.destination.y,30,15);}
    if(t&&this.mode==='rally'){const p=this.sim.level.slots[t.slot],r=this.sim.stats(t).range;this.range.lineStyle(3,0x8ce3e0,.9).strokeCircle(p.x,p.y,r);const cursor=this.input.activePointer,n=this.sim.nearestRoad(cursor),valid=n.distance<=90&&distance(p,n.point)<=r;this.range.lineStyle(3,valid?0x8cf4db:0xff7d6d,.9).strokeCircle(n.point.x,n.point.y,24);for(let i=0;i<3;i++){const q=this.sim.formation(n.point,i);this.range.fillStyle(valid?0x8cf4db:0xff7d6d,.5).fillCircle(q.x,q.y,5);}}
    if(this.heroSelected&&this.sim.hero.hp>0){const h=this.sim.hero;this.range.lineStyle(2,0xffe28f,.9);let last:Point=h;for(const p of h.waypoints){this.range.lineBetween(last.x,last.y,p.x,p.y);this.range.strokeCircle(p.x,p.y,6);last=p;}this.range.strokeCircle(h.anchor.x,h.anchor.y,13);}
    if(this.lessonTarget==='plot'||this.lessonTarget==='tower'){const p=this.lessonTarget==='plot'?this.sim.level.slots.find((_,i)=>!this.sim!.towerAt(i)):this.sim.level.slots[this.sim.towers[0]?.slot];if(p){const y=p.y-85+Math.sin(this.wall*4)*5;this.range.lineStyle(3,0xffe39a,.95).strokeEllipse(p.x,p.y,105,55);this.range.fillStyle(0xffe39a,1).fillTriangle(p.x-10,y-17,p.x+10,y-17,p.x,y);}}
    const pointer=this.input.activePointer;if(this.mode==='meteor'||this.mode==='reinforce'){const color=this.mode==='meteor'?0xffd071:0x8cf4db;this.range.lineStyle(3,color,.9).strokeCircle(pointer.x,pointer.y,this.mode==='meteor'?((this.sim!.upgrades.meteor>=3?75:60)*900/768):35);this.range.fillStyle(color,.12).fillCircle(pointer.x,pointer.y,this.mode==='meteor'?((this.sim!.upgrades.meteor>=3?75:60)*900/768):35);}
    for(const w of this.sim.warnings){const phase=(w.at-this.sim.time)/(w.kind==='meteor'?1.25:1.5);this.range.lineStyle(4,w.kind==='boss'?0xff6955:0xffd277,.6+.3*Math.sin(this.sim.time*14)).strokeCircle(w.point.x,w.point.y,w.radius);this.range.fillStyle(w.kind==='boss'?0xff6955:0xffd277,.18).fillCircle(w.point.x,w.point.y,w.radius*(1-phase));}
  }
  update(_time:number,delta:number){this.wall+=this.sim?(this.paused?0:Math.min(delta/1000,.15)*this.speed):delta/1000;this.artClock+=delta/1000;this.tweens.timeScale=this.sim?(this.paused?0:this.speed):1;
    if(this.sim&&!this.paused){this.accumulator+=Math.min(delta/1000,.15)*this.speed;while(this.accumulator>=STEP){this.previousPositions.clear();for(const unit of [...this.sim.enemies,...this.sim.allies])this.previousPositions.set(unit.id,{x:unit.x,y:unit.y});this.sim.step();this.accumulator-=STEP;}this.syncTowers();this.syncUnits();this.consumeEvents();}
    if(!this.editorActive)this.drawRanges();if(this.sim&&!this.editorActive)this.combatFx.draw(this.wall,this.sim,this.lowQuality);
    const keep:Particle[]=[];for(const p of this.particles){const t=Math.min(1,(this.wall-p.start)/(p.end-p.start));p.image.setPosition(p.from.x+(p.to.x-p.from.x)*t,p.from.y+(p.to.y-p.from.y)*t-(p.kind==='engineer'?Math.sin(t*Math.PI)*80:0));if(p.kind==='burst')p.image.setAlpha(1-t).setScale(.5*(1-t));if(t>=1){p.image.setVisible(false);this.particlePool.push(p.image);}else keep.push(p);}this.particles=keep;
    this.decor.clear();if(!this.lowQuality)for(let i=0;i<16;i++){const x=100+(i*239)%1400+Math.sin(this.wall*.3+i)*16,y=160+(i*139)%550+Math.cos(this.wall*.5+i)*15;this.decor.fillStyle(0xfff1a5,.22+.2*Math.sin(this.wall*2+i)).fillCircle(x,y,2);}
    if(this.artMode){this.artEntries.slice(this.artPage*16,this.artPage*16+16).forEach((entry,i)=>{const id=10000+i;let rig=this.units.get(id);if(!rig){rig=new UnitRig(this,entry.sheet,entry.row,entry.size,entry.columns,id);this.units.set(id,rig);}const state=Math.floor(this.artClock/3)%6,anim=(['idle','walk','attack','hurt','skill','death']as const)[state],x=300+(i%4)*330+(state===1?(this.artClock%3-1.5)*45:0),y=260+Math.floor(i/4)*180;rig.draw({id,kind:entry.kind,x,y,hp:100,maxHp:100,walkDistance:this.artClock*45,moving:state===1,facing:[1,-1,0,2][Math.floor(this.artClock/18)%4],lastHit:anim==='hurt'?this.artClock-this.artClock%.5:-10,anim,animUntil:this.artClock+(anim==='skill'?.8:.4)-(this.artClock%(anim==='skill'?.8:.4))}as AllyState,this.artClock,entry.sheet==='heroes');});}
    this.hudTimer+=delta;if(this.hudTimer>100){this.hudTimer=0;this.hooks.tick();}
  }
}

