import {queueEnemy,enemyDeath,nativeAllyDeath,nativeEnemyContact,updateNativeEnemy,nativeWaveEvents,updateNativeFacilities} from './reference-combat';
import {heroSnapshot,heroXpFactor,updateHeroMechanics} from './hero-mechanics';
import {F,HERO_LEVELS,NATIVE,REFERENCE_SCALE} from '../content/reference-gameplay';
import { ENEMIES, HEROES, TOWERS } from '../content/definitions';
import { Navigation } from './navigation';
import { clamp, distance, Road, SpatialGrid, Random } from './math';
import type { AllyState, CombatEvent, DamageKind, Difficulty, EnemyKind, EnemyState, HeroKind, LevelDefinition, PlayerCommand, Point, Status, TowerKind, TowerState } from './types';
type PendingHit={effect?:string;at:number;target?:number;point:Point;damage:number;kind:DamageKind;radius?:number;air?:boolean;status?:Omit<Status,'remaining'> & {remaining:number};source?:number};
type PendingSpawn={from?:Point;forcedWaypoint?:Point;hp?:number;progress?:number;bounty?:number;generation?:number;at:number;kind:EnemyKind;path:number;subPath?:number;node?:number};
type Warning={at:number;point:Point;kind:'meteor'|'boss';radius:number;damage:number};
export const STEP=1/30;
export class Simulation {
  time=0;gold:number;lives=20;wave=0;nextWaveAt=Infinity;result:'playing'|'won'|'lost'='playing';
  laneRoads:Road[][]=[];waveTiming:'clear'|'original'='clear';waveCompleteAt=Infinity;roads:Road[];towers:TowerState[]=[];enemies:EnemyState[]=[];allies:AllyState[]=[];events:CombatEvent[]=[];
  nativeState:Record<string,number>={};
  goalDistances=new Map<Road,number>();
  heroMines:{point:Point;at:number;until:number;damage:number}[]=[];heroFields:{point:Point;radius:number;until:number;next:number;slow:number}[]=[];
  zones:{point:Point;until:number;next:number}[]=[];hits:PendingHit[]=[];spawns:PendingSpawn[]=[];warnings:Warning[]=[];cooldowns={reinforce:0,meteor:0};
  hero:AllyState;id=1;eventId=1;kills=0;heroDamage=0;grid=new SpatialGrid<EnemyState>();
  navigation:Navigation;autoWave=true;rng=new Random(9451);facilityStates=new Map<string,{rank:number;next:number;thawed:boolean}>();finalBossStarted=false;
  rngSeed=9451;autoWaveAt=Infinity;waveActive=false;metrics={towers:{} as Record<string,{damage:number;overkill:number;control:number;investment:number;blockedSeconds:number;deaths:number}>,blockedSeconds:0,allyDeaths:0,leaks:0,aoeHits:0};
  lastError='';bossPassUntil=new Map<number,number>();blocked=new Map<number,AllyState>();
  constructor(public level:LevelDefinition,public heroKind:HeroKind='shield',public difficulty:Difficulty='normal',public upgrades:Record<string,number>={},seed=9451) {
    this.rngSeed=seed;this.rng=new Random(seed);this.gold=level.gold;this.lives=level.lives??20;this.roads=level.paths.map(p=>new Road(p,level.densePaths));this.laneRoads=(level.subPaths??level.paths.map(p=>[p])).map(lanes=>lanes.map(p=>new Road(p,level.densePaths)));this.navigation=new Navigation(level,this.roads);this.upgrades=Object.fromEntries(Object.entries(upgrades).map(([k,v])=>[k,Math.min(v,level.maxUpgrade??5)]));const h=HEROES[heroKind];
    for(const f of level.facilities??[])this.facilityStates.set(f.id,{rank:0,next:f.every??60,thawed:false});
    this.hero={id:this.id++,kind:heroKind,x:level.heroStart.x,y:level.heroStart.y,destination:{...level.heroStart},waypoints:[],anchor:{...level.heroStart},commanded:false,walkDistance:0,hp:h.hp,maxHp:h.hp,attackCd:0,specialCd:3,secondaryCd:6,lastHit:-100,revive:0,armor:h.armor,moving:false,facing:1,anim:'idle',animUntil:0,level:1,xp:0,buffUntil:0};
    for(const preset of level.prebuilt??[]){const p=level.slots[preset.slot];if(!p)continue;const branch=preset.level===4?preset.branch??0:-1,spent=Array.from({length:preset.level},(_,i)=>this.price(preset.kind,i,Math.max(0,branch))).reduce((a,b)=>a+b,0);const t:TowerState={slot:preset.slot,kind:preset.kind,level:preset.level,branch,spent,attackCd:.5,skillCd:4,secondaryCd:7,skills:[0,0,0],sealAt:0,rally:level.defaultRallies?.[preset.slot]??this.nearestRoad(p).point,disabledUntil:0,firedAt:-10};this.towers.push(t);if(t.kind==='barracks')for(let i=0;i<3;i++)this.createSoldier(t,i);}
    if(level.heroes!==false)this.allies.push(this.hero);else this.hero.hp=0;for(const f of level.facilities??[])if(f.kind==='guards')for(let i=0;i<7;i++){const a=this.createSoldier(undefined,i,f);a.kind='elf';a.hp=a.maxHp=150;a.armor=.3;a.expires=Infinity;this.route(a,this.roads[f.path].at(f.progress*this.roads[f.path].total));}for(const ev of level.scriptEvents??[])if(ev.template==='soldier_s6_imperial_guard'&&ev.point){const base=NATIVE[ev.template],a=this.createSoldier(undefined,0,ev.point);a.kind='ancestor';a.summon={template:ev.template,minDamage:10,damage:30,range:base.melee.range*REFERENCE_SCALE,speed:base.motion.max_speed*REFERENCE_SCALE,interval:base.melee.cooldown,damageKind:'physical'};a.hp=a.maxHp=base.health.hp_max*(difficulty==='casual'?1.2:1);a.armor=base.health.armor;a.commanded=false;a.destination={...ev.point};a.anchor={...ev.point};a.waypoints=[];}
  }
  emit(type:CombatEvent['type'],point:Point,details:Partial<CombatEvent>={}){this.events.push({id:this.eventId++,type,at:this.time,point:{...point},...details});}
  recordInvestment(slot:number,cost:number){const m=this.metrics.towers[String(slot)]??={damage:0,overkill:0,control:0,investment:0,blockedSeconds:0,deaths:0};m.investment+=cost;}
  recordExecution(e:EnemyState,slot:number){const m=this.metrics.towers[String(slot)]??={damage:0,overkill:0,control:0,investment:0,blockedSeconds:0,deaths:0};m.damage+=e.hp;}
  nearestRoad(p:Point){return this.roads.map(r=>({...r.nearest(p),road:r})).sort((a,b)=>a.distance-b.distance)[0];}
  towerAt(slot:number){return this.towers.find(t=>t.slot===slot);}
  up(key:string,n:number){return (this.upgrades[key]??0)>=n;}
  random(lo:number,hi:number){return lo+this.rng.next()*(hi-lo);}
  price(kind:TowerKind,index:number,branch=0){const d=TOWERS[kind],base=index===3?d.branches[branch].cost:d.costs[index];return Math.floor(base*((kind==='mage'&&this.up('mage',3)||kind==='engineer'&&this.up('engineer',3))?.9:1));}
  skillPrice(t:TowerState,i:number){const d=TOWERS[t.kind].branches[t.branch].skills[i];return Math.floor((d.costs[t.skills[i]]??Infinity)*(t.kind==='engineer'&&this.up('engineer',4)?.75:1));}
  refund(t:TowerState){return Math.floor(t.spent*(this.wave===0?1:t.kind==='archer'&&this.up('archer',1)?.9:.6));}
  maxLevel(kind:TowerKind){return this.level.allowedTowers&&!this.level.allowedTowers.includes(kind)?0:this.level.maxTowerLevel??4;}
  branchOpen(kind:TowerKind,branch:number){return ((this.level.unlocks?.[kind]??3)&(1<<branch))!==0&&(this.level.unlockAtWave?.[kind]??0)<=this.wave;}
  stats(t:TowerState){const d=TOWERS[t.kind],b=t.branch>=0?d.branches[t.branch]:undefined,i=t.level-1;let mult=t.kind==='mage'&&this.up('mage',4)?1.15:t.kind==='engineer'&&this.up('engineer',1)?1.1:1;let range=b?.range??d.range[i];if(this.up(t.kind,2)&&(t.kind==='archer'||t.kind==='engineer'))range*=1.1;if(t.kind==='archer'&&this.up('archer',4))range*=1.1;if(t.kind==='mage'&&this.up('mage',1))range*=1.1;if(t.kind==='barracks'&&this.up('barracks',3))range*=1.2;return{minDamage:(b?.minDamage??d.minDamage[i])*mult,damage:(b?.damage??d.damage[i])*mult,range:range*((t.buffUntil??0)>this.time?1.2:1),interval:(b?.interval??d.interval[i])*((t.buffUntil??0)>this.time?.8:1),kind:d.damageKind,air:d.air||t.kind==='engineer'&&t.branch===1};}
  command(c:PlayerCommand):boolean {
    this.lastError='';if(this.result!=='playing')return false;
    const fail=(s:string)=>{this.lastError=s;return false;};
    if(c.type==='auto-wave'){this.autoWave=c.enabled;this.autoWaveAt=Infinity;return true;}
    if(c.type==='unseal'){const t=this.towerAt(c.slot);if(!t)return false;if(t.sealAt){t.sealClicks=Math.max(0,(t.sealClicks??1)-1);if(!t.sealClicks)t.sealAt=0;}else if(t.iceClicks){t.iceClicks--;if(!t.iceClicks)t.disabledUntil=this.time;}return true;}
    if(c.type==='pop-sheep'){const e=this.enemies.find(e=>e.id===c.id&&e.sheep);if(!e)return false;e.hp=0;this.kill(e);return true;}
    if(c.type==='facility')return this.facility(c.id,c.point);
    if(c.type==='build') {
      if(!this.level.slots[c.slot]||this.towerAt(c.slot)||!TOWERS[c.kind]||this.maxLevel(c.kind)<1)return fail('此处无法建造');
      const cost=this.price(c.kind,0);if(this.gold<cost)return fail('金币不足');this.gold-=cost;
      const p=this.level.slots[c.slot],r=this.level.defaultRallies?.[c.slot]??this.nearestRoad(p).point;
      const t:TowerState={slot:c.slot,kind:c.kind,level:1,branch:-1,spent:cost,attackCd:.5,skillCd:4,secondaryCd:7,skills:[0,0,0],sealAt:0,rally:{...r},disabledUntil:0,firedAt:-10};this.towers.push(t);this.recordInvestment(c.slot,cost);
      if(c.kind==='barracks')for(let i=0;i<3;i++)this.createSoldier(t,i);
      this.emit('upgrade',p,{kind:'build'});return true;
    }
    if(c.type==='upgrade') {
      const t=this.towerAt(c.slot);if(!t||t.level>=this.maxLevel(t.kind))return fail('无法继续升级');
      if(t.level===3&&c.branch!==0&&c.branch!==1)return fail('请选择高级塔分支');
      if(t.level===3&&!this.branchOpen(t.kind,c.branch!))return fail('此分支尚未解锁');const cost=this.price(t.kind,t.level,c.branch??0);if(this.gold<cost)return fail('金币不足');this.gold-=cost;t.spent+=cost;this.recordInvestment(t.slot,cost);t.level++;
      if(t.level===4)t.branch=c.branch!;
      if(t.kind==='barracks')for(const a of this.allies.filter(a=>a.tower===t.slot)){const old=a.maxHp;this.soldierStats(a,t);a.hp=a.maxHp;a.revive=0;void old;}
      this.emit('upgrade',this.level.slots[t.slot]);return true;
    }
    if(c.type==='tower-skill') {
      const t=this.towerAt(c.slot);if(!t||t.branch<0||c.skill<0||c.skill>=TOWERS[t.kind].branches[t.branch].skills.length||t.skills[c.skill]>=TOWERS[t.kind].branches[t.branch].skills[c.skill].maxLevel)return fail('此技能无法购买');
      const skill=TOWERS[t.kind].branches[t.branch].skills[c.skill];const cost=this.skillPrice(t,c.skill);if(this.gold<cost)return fail('金币不足');this.gold-=cost;t.spent+=cost;this.recordInvestment(t.slot,cost);t.skills[c.skill]++;if(t.kind==='mage'&&t.branch===1&&c.skill===1&&!this.allies.some(a=>a.kind==='elemental'&&a.tower===t.slot)){const a=this.createSoldier(t);a.kind='elemental';a.hp=a.maxHp=600;a.armor=.4;}if(t.kind==='barracks')for(const a of this.allies.filter(a=>a.tower===t.slot)){this.soldierStats(a,t);a.hp=a.maxHp;}this.emit('upgrade',this.level.slots[t.slot],{text:skill.name});return true;
    }
    if(c.type==='sell') {const t=this.towerAt(c.slot);if(!t)return false;this.gold+=this.refund(t);this.towers=this.towers.filter(x=>x!==t);this.allies=this.allies.filter(a=>a.tower!==t.slot);this.emit('upgrade',this.level.slots[t.slot],{kind:'sell'});return true;}
    if(c.type==='rally') {const t=this.towerAt(c.slot);if(!t||(t.kind!=='barracks'&&!this.allies.some(a=>a.tower===t.slot&&a.kind==='elemental')))return fail('请选择守卫营');const n=this.nearestRoad(c.point);if(n.distance>90||distance(this.level.slots[t.slot],n.point)>this.stats(t).range)return fail('集结点必须位于营地范围内的道路');t.rally={...n.point};for(const [i,a]of this.allies.filter(a=>a.tower===t.slot).entries())this.route(a,this.formation(t.rally,i));this.emit('skill',n.point,{kind:'rally'});return true;}
    if(c.type==='move-hero'){if(this.level.heroes===false)return fail('本关尚未开放英雄');if(this.hero.hp<=0)return fail('英雄正在复活');const goal=this.navigation.snap(c.point);if(!goal)return fail('该位置不可通行');if(this.hero.charge){this.hero.charge=undefined;this.hero.immuneUntil=undefined;}const from=c.append?this.hero.waypoints.at(-1)??this.hero:this.hero;const route=this.navigation.path(from,goal);if(!route)return fail('此处无法到达');this.hero.waypoints=c.append?[...this.hero.waypoints,...route]:route;this.hero.destination={...goal};this.hero.anchor={...goal};this.hero.commanded=true;if(HEROES[this.heroKind].teleport&&!c.append&&distance(this.hero,goal)>130*REFERENCE_SCALE){Object.assign(this.hero,goal);this.hero.waypoints=[];this.hero.commanded=false;this.emit('teleport',goal,{actor:this.hero.id});}return true;}
    if(c.type==='cast') {
      if(!Number.isFinite(c.point.x)||!Number.isFinite(c.point.y)||c.point.x<0||c.point.x>1600||c.point.y<0||c.point.y>900)return fail('请选择战场内的位置');
      if(this.level.lockedPowers?.[c.skill==='meteor'?0:1])return fail('本关尚未开放此技能');if(this.cooldowns[c.skill]>0)return fail('技能正在冷却');const up=this.upgrades[c.skill]??0;
      if(c.skill==='reinforce'){const n=this.nearestRoad(c.point);if(n.distance>85)return fail('援军需要部署在道路上');this.cooldowns.reinforce=10;for(let i=0;i<2;i++){const a=this.createSoldier(undefined,i,n.point);a.expires=this.time+20;a.maxHp=a.hp=this.soldierTemplate()?.health.hp_max??30;a.armor=this.soldierTemplate()?.health.armor??0;}this.emit('skill',n.point,{kind:'reinforce'});}
      else{this.cooldowns.meteor=up>=4?60:up>=3?70:80;for(let i=0;i<(up>=5?10:up>=1?5:3);i++){const scatter=up>=5&&i>=5?{x:this.random(100,1500),y:this.random(150,800)}:{x:c.point.x+this.random(-20,20)*REFERENCE_SCALE,y:c.point.y+this.random(-20,20)*REFERENCE_SCALE};this.warnings.push({at:this.time+1.25+i*.3,point:scatter,kind:'meteor',radius:(up>=3?75:60)*REFERENCE_SCALE,damage:this.random(up>=5?150:up>=3?90:up>=1?50:30,up>=5?180:up>=3?120:up>=1?80:60)});}for(const f of this.level.facilities??[])if(f.kind==='sasquatch'&&distance(f,c.point)<170)this.facilityStates.get(f.id)!.thawed=true;this.emit('warning',c.point,{kind:'meteor',amount:1.25});}
      return true;
    }
    if(c.type==='next-wave'){if(this.wave>=this.level.waves.length)return fail('已经是最后一波');if(Number.isFinite(this.nextWaveAt)){const bonus=Math.max(0,Math.ceil(this.nextWaveAt-this.time));this.gold+=bonus;for(const k of ['reinforce','meteor']as const)this.cooldowns[k]=Math.max(0,this.cooldowns[k]-Math.max(0,this.nextWaveAt-this.time));if(bonus)this.emit('skill',{x:800,y:150},{text:`提前开波 +${bonus} 金币`,kind:'bonus'});}this.startWave();return true;}
    return false;
  }
  formation(p:Point,i:number):Point{return{x:p.x+(i%3-1)*22,y:p.y+(i%2)*17-8};}
  route(a:AllyState,p:Point){const goal=this.navigation.snap(p,160)??p;a.destination={...goal};a.anchor={...goal};a.waypoints=this.navigation.path(a,goal)??[goal];a.commanded=true;}
  soldierTemplate(t?:TowerState){return t?NATIVE[t.branch===0?'soldier_paladin':t.branch===1?'soldier_barbarian':['soldier_militia','soldier_footmen','soldier_knight'][t.level-1]]:NATIVE[['re_farmer','re_farmer_well_fed','re_conscript','re_warrior','re_legionnaire','re_legionnaire_ranged'][Math.min(5,this.upgrades.reinforce??0)]];}
  soldierStats(a:AllyState,t?:TowerState){if(a.kind==='elemental')return;const base=this.soldierTemplate(t);a.maxHp=(base?.health.hp_max??30)*(t?(this.up('barracks',4)?1.2:this.up('barracks',1)?1.1:1):1)*(this.difficulty==='casual'?1.2:1);a.armor=(base?.health.armor??0)+(t&&this.up('barracks',2)?.1:0)+(t?.branch===0&&t.skills[1]?.15:0);}
  createSoldier(t?:TowerState,index=0,point?:Point):AllyState {
    const p=point??this.level.slots[t!.slot],goal=this.formation(t?.rally??p,index);
    const a:AllyState={id:this.id++,kind:'soldier',tower:t?.slot,x:p.x,y:p.y,destination:goal,waypoints:[],anchor:{...goal},commanded:true,walkDistance:0,hp:105,maxHp:105,attackCd:.2,specialCd:3+index,secondaryCd:5,lastHit:-100,revive:0,armor:.08,moving:false,facing:1,anim:'idle',animUntil:0,level:1,xp:0,buffUntil:0};this.soldierStats(a,t);a.hp=a.maxHp;this.allies.push(a);this.route(a,goal);return a;
  }
  enemyRoad(e:EnemyState){return this.laneRoads[e.path]?.[e.subPath??0]??this.roads[e.path];}
  terrain(p:Point){const g=this.level.walkingGrid,l=this.level.logicalSize;if(!g||!l)return 1;const x=Math.floor(((p.x-l.offsetX)/l.scale-g.ox)/16),y=Math.floor(((900-p.y)/l.scale-g.oy)/16);return g.grid[x]?.[y]??0;}
  canBlock(e:EnemyState){return !e.sheep&&!this.isFlying(e)&&!(ENEMIES[e.kind].native==='enemy_troll_skater'&&(this.terrain(e)&2048));}
  canAffect(e:EnemyState,effect:'instakill'|'disintegrate'|'polymorph'|'teleport'|'thorn'){const flag=effect==='instakill'?F.F_INSTAKILL:effect==='disintegrate'?F.F_DISINTEGRATED:effect==='polymorph'?F.F_POLYMORPH:effect==='thorn'?F.F_THORN:F.F_TELEPORT;return !ENEMIES[e.kind].behavior.boss&&!((NATIVE[ENEMIES[e.kind].native??'']?.vis?.bans??0)&flag);}
  connectedPath(path:number):number|undefined{const c=this.level.pathConnections;if(Array.isArray(c))return c[path]?Number(c[path])-1:undefined;const next=(c as Record<string,number>|undefined)?.[String(path+1)+'.0']??(c as Record<string,number>|undefined)?.[String(path+1)];return next?next-1:undefined;}
  goalProgress(e:EnemyState){const r=this.enemyRoad(e);let goal=this.goalDistances.get(r);if(goal===undefined){const end=this.level.pathEnds?.[e.path];if(end!==undefined)goal=r.lengths[end]??r.total;else{const exit=this.level.exitPoints?.map(p=>r.nearest(p)).sort((a,b)=>a.distance-b.distance)[0];goal=exit&&exit.distance<55*REFERENCE_SCALE?exit.progress:r.total;}this.goalDistances.set(r,goal);}return goal;}
  remainingDistance(e:EnemyState){let total=this.goalProgress(e)-e.distance,path=e.path;const seen=new Set([path]);while(this.connectedPath(path)!==undefined){path=this.connectedPath(path)!;if(seen.has(path))break;seen.add(path);total+=this.goalProgress({...e,path});}return total;}
  startWave(){const w=this.level.waves[this.wave];if(!w)return;this.wave++;this.autoWaveAt=Infinity;this.waveActive=true;let end=0;nativeWaveEvents(this);
    const timeline=w.timelines?.[String(this.rngSeed)]??w.timeline;
    if(timeline){for(const e of timeline){const delay=e.tick/30;end=Math.max(end,delay);this.spawns.push({at:this.time+delay,kind:e.type,path:e.path,subPath:e.subPath,node:e.node});}end=Math.max(end,(w.completeTicks?.[String(this.rngSeed)]??w.completeTick??0)/30);}
    else for(const g of w.groups)for(let i=0;i<g.count;i++){const delay=g.delay+i*g.interval;end=Math.max(end,delay);this.spawns.push({at:this.time+delay,kind:g.type,path:g.path});}
    this.spawns.sort((a,b)=>a.at-b.at);this.waveCompleteAt=this.time+end;
    this.nextWaveAt=this.wave<this.level.waves.length?this.time+(this.level.waves[this.wave]?.originalInterval??end+w.rest):Infinity;
    this.emit('wave',{x:800,y:180},{text:`第 ${this.wave} 波`,amount:this.wave});
  }
  spawn(kind:EnemyKind,path=0,progress=0,mini=false,subPath=0):EnemyState {
    const def=ENEMIES[kind],p=(this.laneRoads[path]?.[subPath]??this.roads[path]).at(progress),mult=this.difficulty==='casual'?.8:this.difficulty==='veteran'||this.difficulty==='challenge'?1.2:1;
    const hp=(def.difficultyHp?.[this.difficulty==='casual'?0:this.difficulty==='normal'?1:2]??def.hp*mult)*(mini?.3:1);const e:EnemyState={id:this.id++,kind,...p,hp,maxHp:hp,path,subPath,distance:progress,attackCd:.6,specialCd:kind==='boss'?9:5,statuses:[],lastHit:-100,moving:true,facing:1,anim:'walk',animUntil:0,phase:mini?-1:0,blockTime:0,armor:def.armor,bounty:mini?0:def.gold,teleports:0,roots:0,sheep:false,deathPaid:false,shieldUntil:0};this.enemies.push(e);if(this.wave>0){this.waveActive=true;this.autoWaveAt=Infinity;}this.emit('spawn',p,{kind});return e;
  }
  isFlying(e:EnemyState){return !!ENEMIES[e.kind].flying||(e.flyingUntil??0)>this.time;}
  targets(p:Point,range:number,air=true){return this.grid.around(p,range).filter(e=>e.hp>0&&(air||!this.isFlying(e))).sort((a,b)=>this.remainingDistance(a)/ENEMIES[a.kind].speed-this.remainingDistance(b)/ENEMIES[b.kind].speed||a.id-b.id);}
  addStatus(e:EnemyState,type:Status['type'],remaining:number,power:number,source?:number,details:Partial<Status>={}){if(ENEMIES[e.kind].behavior.controlImmune&&['stun','freeze','root'].includes(type))return;if(type==='poison'&&ENEMIES[e.kind].behavior.poisonImmune)return;const old=e.statuses.find(s=>s.type===type);if(old){old.remaining=Math.max(old.remaining,remaining);old.power=Math.max(old.power,power);if(source!==undefined)old.source=source;}else e.statuses.push({type,remaining,power,source,...details});}
  damage(e:EnemyState,amount:number,kind:DamageKind,source?:number){if(e.hp<=0)return;const def=ENEMIES[e.kind];const immune=NATIVE[def.native??'']?.health?.immune_to??0;if(immune & (kind==='physical'?2:kind==='magic'?4:kind==='explosive'?8:1))return;if(e.shieldHits){e.shieldHits--;this.emit('impact',e,{kind:'shield'});return;}if(kind==='physical'&&def.behavior.dodge&&this.rng.next()<def.behavior.dodge){this.emit('skill',e,{kind:'dodge'});return;}const armor=e.armor*(e.statuses.some(s=>s.type==='curse')?.5:1);const mitigation=kind==='physical'?Math.max(0,armor*(source!==undefined&&source<0&&this.towerAt(-100-source)?.kind==='archer'&&this.up('archer',3)?.9:1)):kind==='explosive'?armor*.5:kind==='magic'?def.resist:0;const mark=e.statuses.some(s=>s.type==='mark')?1.3:1;const potential=amount*(1-mitigation)*mark*(e.shieldUntil>this.time?.25:1),actual=Math.min(e.hp,potential);e.hp-=actual;e.lastHit=this.time;const slot=this.sourceSlot(source);if(slot!==undefined){const k=String(slot),m=this.metrics.towers[k]??={damage:0,overkill:0,control:0,investment:0,blockedSeconds:0,deaths:0};m.damage+=actual;m.overkill+=Math.max(0,potential-actual);m.investment=Math.max(m.investment,this.towerAt(slot)?.spent??0);}
    if(kind==='magic'&&source!==undefined&&source<0&&this.towerAt(-100-source)?.kind==='mage'&&this.up('mage',2))e.armor=Math.max(0,e.armor-.03);if(kind==='magic'&&source!==undefined&&source<0&&this.towerAt(-100-source)?.kind==='mage'&&this.up('mage',5)&&!NATIVE.mod_slow_curse.modifier.excluded_templates.includes(def.native))this.addStatus(e,'slow',.5,.5,source);if(source===this.hero.id){this.heroDamage+=actual;this.hero.xp+=actual*heroXpFactor(this.hero);this.levelHero();}
    if(e.hp<=0)this.kill(e);else if(e.anim!=='attack'&&e.anim!=='skill'){e.anim='hurt';e.animUntil=this.time+.14;}
  }
  levelHero(){const thresholds=[0,300,900,2000,4000,8000,12000,16000,20000,26000];while(this.hero.level<10&&this.hero.xp>=thresholds[this.hero.level]){this.hero.level++;const stats=HEROES[this.heroKind].levelStats![this.hero.level-1];this.hero.maxHp=stats.hp;this.hero.armor=stats.armor;this.hero.hp=this.hero.maxHp;this.emit('upgrade',this.hero,{text:'英雄 Lv.'+this.hero.level});}}
  kill(e:EnemyState){if(e.deathPaid)return;const def=ENEMIES[e.kind];if(def.behavior.boss==='thorn'&&e.phase===0){e.phase=1;e.maxHp=ENEMIES[e.kind].difficultyHp?.[this.difficulty==='casual'?0:this.difficulty==='normal'?1:2]??ENEMIES[e.kind].hp;e.hp=e.maxHp;e.specialCd=2;this.emit('warning',e,{kind:'rage',text:'荆棘巨兽显露真身！'});return;}e.deathPaid=true;enemyDeath(this,e);this.gold+=e.bounty;this.kills++;this.emit('death',e,{kind:e.kind,phase:e.phase,morphed:e.sheep,actor:e.id,amount:e.bounty});if(['eb_juggernaut','eb_jt','eb_veznan','eb_moloch','eb_blackburn'].includes(def.native??'')){this.spawns=[];for(const other of this.enemies)if(other!==e){other.hp=0;other.deathPaid=true;}}if(def.behavior.split&&e.phase!==-1){this.spawn(def.behavior.split,e.path,Math.max(0,e.distance-12),true);this.spawn(def.behavior.split,e.path,e.distance+12,true);}if(def.behavior.explode)for(const a of this.allies.filter(a=>a.hp>0&&distance(a,e)<95))this.hitAlly(a,def.behavior.explode);if(!def.behavior.boss&&!e.sheep&&['mushroom','orc','bandit','boar','marauder','shadow','knight','slayer'].includes(e.kind))for(const f of this.level.facilities??[])if(f.kind==='graveyard'){const n=this.spawn(def.hp<300?'skeleton':'skeletonknight',f.path,this.roads[f.path].total*f.progress);n.bounty=0;}if(this.level.referenceBuild!==24662480&&(def.behavior.boss==='juggernaut'||def.behavior.boss==='thorn'&&e.phase===1)){this.spawns=[];for(const other of this.enemies)if(other!==e)other.hp=0;this.finish('won');}}
  hitAlly(a:AllyState,damage:number,kind:DamageKind='physical'){if(a.hp<=0||(a.immuneUntil??0)>this.time)return;const armor=Math.min(.95,a.armor+(a.buffUntil>this.time?.05*(a.courageRank??0):0));a.hp-=damage*(kind==='true'||kind==='magic'?1:1-armor*(kind==='explosive'?.5:1))*(this.difficulty==='challenge'?1.1:1);a.lastHit=this.time;a.anim='hurt';a.animUntil=this.time+.2;
    if(a.hp<=0){nativeAllyDeath(this,a);this.metrics.allyDeaths++;if(a.tower!==undefined){this.recordInvestment(a.tower,0);this.metrics.towers[String(a.tower)].deaths++;}a.hp=0;a.revive=a.kind==='soldier'?(this.soldierTemplate(a.tower!==undefined?this.towerAt(a.tower):undefined)?.health.dead_lifetime??10)*(this.up('barracks',3)?.8:1):a.kind in HEROES?HEROES[a.kind as HeroKind].revive:a.kind==='elemental'?8:a.summon?.template==='soldier_s6_imperial_guard'||a.facility?3:Infinity;this.emit('death',a,{kind:a.kind,actor:a.id,slot:a.tower});}}
  fire(p:Point,e:EnemyState,damage:number,kind:DamageKind,options:{radius?:number;air?:boolean;status?:Status;source?:number;color?:number;shot?:string}={}){
    const flight=options.radius?.52:Math.min(.5,distance(p,e)/(850*REFERENCE_SCALE)+.08);this.hits.push({at:this.time+flight,target:e.id,point:{x:e.x,y:e.y},damage,kind,radius:options.radius,air:options.air,status:options.status,source:options.source});
    this.emit('shot',p,{target:{x:e.x,y:e.y},damageKind:kind,color:options.color??(kind==='magic'?0x83dfff:0xffd977),kind:options.shot,effect:options.shot,amount:flight,targetId:e.id,radius:options.radius,...this.effectDetails(options.source)});
  }
  area(p:Point,radius:number,damage:number,kind:DamageKind,status?:Status,source?:number,air=true){const victims=this.grid.around(p,radius).filter(e=>e.hp>0&&(air||!this.isFlying(e)));if(victims.length>=2&&kind==='explosive')this.metrics.aoeHits++;for(const e of victims){this.damage(e,damage*(kind==='explosive'&&!this.up('engineer',5)?Math.max(.5,1-distance(p,e)/radius*.5):1),kind,source);if(e.hp>0&&status)this.addStatus(e,status.type,status.remaining,status.power,source);}this.emit('impact',p,{kind:status?.type,color:kind==='magic'?0x83dfff:0xffbc58,amount:radius,radius,damageKind:kind,...this.effectDetails(source)});}
  updateTowers(dt:number){for(const t of this.towers){t.attackCd-=dt;t.skillCd-=dt;t.secondaryCd-=dt;if(t.disabledUntil<=this.time)t.iceClicks=0;if(t.sealAt&&t.sealAt<=this.time){t.disabledUntil=this.time+6;t.sealAt=0;}if(t.disabledUntil>this.time)continue;const p=this.level.slots[t.slot],stats=this.stats(t);
    if(t.kind==='barracks'){
      
      
      continue;
    }
    if(t.attackCd<=0){const e=this.targets(p,stats.range,stats.air)[0];if(e){t.attackCd=stats.interval;t.firedAt=this.time;
      let damage=this.random(stats.minDamage,stats.damage)*(t.kind==='archer'&&this.up('archer',5)&&this.rng.next()<.1?2:1), radius=t.kind==='engineer'?(t.branch===0?67.5:t.level===3?67.2:62.4)*REFERENCE_SCALE:undefined,kind=stats.kind,status:Status|undefined;
      if(t.kind==='archer'&&t.branch===0&&t.skills[0])status={type:'poison',remaining:3,power:5*t.skills[0]};
      if(t.kind==='mage'&&t.branch===1)status={type:'curse',remaining:4.9,power:8};
      
      
      if(t.kind==='engineer'&&t.branch===1){kind='explosive';radius=undefined;const seen=new Set<number>();let target:EnemyState|undefined=e,from:Point=p;for(let i=0;target&&i<3+t.skills[0];i++){seen.add(target.id);if(ENEMIES[target.kind].native!=='enemy_spectral_knight')this.fire(from,target,damage*(this.up('engineer',5)?2:1),kind,{shot:'lightning',source:-100-t.slot});from=target;target=this.targets(from,95*REFERENCE_SCALE,true).filter(n=>!seen.has(n.id)).sort((a,b)=>distance(a,from)-distance(b,from))[0];}if(t.skills[1]){this.area(p,stats.range,this.random(0,10)+10*t.skills[1],'explosive',undefined,-100-t.slot,true);this.hits.push({at:this.time+.5,point:p,radius:stats.range,damage:this.random(0,10)+10*t.skills[1],kind:'explosive',air:true,source:-100-t.slot});}}
      else this.fire({x:p.x,y:p.y-80},e,damage,kind,{radius,air:stats.air,status,shot:t.kind,source:-100-t.slot});
    }}
    if(t.branch>=0)this.advanced(t,p,stats);

  }}
  updateAllies(dt:number){
    this.metrics.blockedSeconds+=this.blocked.size*dt;for(const a of this.blocked.values())if(a.tower!==undefined){this.recordInvestment(a.tower,0);this.metrics.towers[String(a.tower)].blockedSeconds+=dt;}this.blocked.clear();const taken=new Set<number>();
    for(const a of this.allies){
      a.attackCd-=dt;a.specialCd-=dt;a.secondaryCd-=dt;
      const t=a.tower!==undefined?this.towerAt(a.tower):undefined,h=a.kind in HEROES?HEROES[a.kind as HeroKind]:undefined;
      const template=h?heroSnapshot(a):a.summon?NATIVE[a.summon.template]:a.kind==='soldier'?this.soldierTemplate(t):NATIVE[a.kind==='elemental'?'soldier_elemental':a.kind==='elf'?'soldier_elf':'soldier_sasquash'];
      if(a.hp<=0){a.revive-=dt;if(a.revive<=0&&(!a.expires||a.facility)){if(a.kind==='soldier'&&!t)continue;a.hp=a.maxHp;const facility=a.facility?this.level.facilities?.find(f=>f.id===a.facility):undefined;const p=facility??(t?this.level.slots[t.slot]:a.summon?.template==='soldier_s6_imperial_guard'?a.anchor:this.level.heroStart);a.x=p.x;a.y=p.y;a.heroCds={};a.transformedUntil=undefined;a.immuneUntil=undefined;this.route(a,a.anchor);this.emit('spawn',a,{kind:a.kind});}continue;}
      if((a.stunnedUntil??0)>this.time){a.moving=false;continue;}if(a.expires&&this.time>=a.expires){a.hp=0;continue;}
      if(a.kind==='elemental'&&t){const rank=t.skills[1];a.maxHp=(500+100*rank)*(this.difficulty==='casual'?1.2:1);a.armor=.3+.1*rank;}
      if(a.kind==='pet'&&!a.commanded&&distance(a,this.hero)>220*REFERENCE_SCALE)this.route(a,this.hero);
      const range=h?.range??a.summon?.range??((a.kind==='soldier'&&!t&&this.up('reinforce',5)?230:template?.ranged?.attacks?.[0]?.max_range??template?.melee?.range??60)*REFERENCE_SCALE),block=h?.block??1;
      if(h&&h.range<100*REFERENCE_SCALE&&!a.commanded){const target=this.targets(a.anchor,130*REFERENCE_SCALE,false).find(e=>!e.sheep);const predicted=target?this.enemyRoad(target).at(target.distance+Math.min(25*REFERENCE_SCALE,ENEMIES[target.kind].speed*distance(a,target)/h.speed)):a.anchor;const goal=distance(predicted,a.anchor)<=150*REFERENCE_SCALE?predicted:a.anchor;if(distance(a.destination,goal)>20){a.destination={x:goal.x,y:goal.y};a.waypoints=this.navigation.path(a,goal)??[];}}
      while(a.waypoints.length&&distance(a,a.waypoints[0])<=3){const reached=a.waypoints.shift()!;a.x=reached.x;a.y=reached.y;if(!a.waypoints.length)a.commanded=false;}
      const goal=a.waypoints[0]??a.destination;let moving=distance(a,goal)>3;
      const targets=this.targets(a,moving?40*REFERENCE_SCALE:range,h?.air??(a.kind==='illusion'||a.kind==='elf'||!t&&this.up('reinforce',5)));
      const ground=targets.filter(e=>(!moving||a.kind==='soldier'&&!a.commanded||!!h&&h.range<100*REFERENCE_SCALE&&!a.commanded)&&this.canBlock(e)&&distance(a,e)<60*REFERENCE_SCALE&&!taken.has(e.id));
      for(const e of ground.slice(0,block)){this.blocked.set(e.id,a);taken.add(e.id);}
      const blockedEnemy=ground.find(e=>this.blocked.get(e.id)===a);a.targetId=(blockedEnemy??targets[0])?.id;if(blockedEnemy)moving=false;a.moving=moving;
      if(moving){const dd=distance(a,goal),speed=(h?.speed??a.summon?.speed??(template?.motion?.max_speed??75)*REFERENCE_SCALE)*(a.charge?NATIVE.hero_ignus.timed_attacks.list[1].speed_factor:1),step=Math.min(dd,speed*dt),dx=(goal.x-a.x)/dd,dy=(goal.y-a.y)/dd;a.x+=dx*step;a.y+=dy*step;a.walkDistance+=step;if(step>=dd-.001){a.waypoints.shift();if(!a.waypoints.length)a.commanded=false;}a.facing=Math.abs(dy)>.8?(dy<0?2:0):(dx>=0?1:-1);}
      const nativeAttack=blockedEnemy?template?.melee?.attacks?.[0]:template?.ranged?.attacks?.[0]??template?.timed_attacks?.list?.find((x:any)=>x.bullet)??template?.melee?.attacks?.[0];
      if(!moving){const e=blockedEnemy??targets[0];if(e&&a.attackCd<=0){
        const ls=h?.levelStats?.[a.level-1];let lo=blockedEnemy?template?.melee?.attacks?.[0]?.damage_min:ls?.minDamage,max=blockedEnemy?template?.melee?.attacks?.[0]?.damage_max:ls?.maxDamage;
        if(!h){lo=a.summon?.minDamage??(t&&a.kind==='soldier'?this.stats(t).minDamage:nativeAttack?.damage_min??1);max=a.summon?.damage??(t&&a.kind==='soldier'?this.stats(t).damage: NATIVE[nativeAttack?.bullet]?.bullet?.damage_max??nativeAttack?.damage_max??3);lo=a.summon?.minDamage??(t&&a.kind==='soldier'?this.stats(t).minDamage:NATIVE[nativeAttack?.bullet]?.bullet?.damage_min??nativeAttack?.damage_min??1);}
        if(a.kind==='elemental'){lo=(nativeAttack?.damage_min??20)+10*(t?.skills[1]??1);max=(nativeAttack?.damage_max??40)+10*(t?.skills[1]??1);}if(a.transformedUntil&&a.kind==='ingvar'){const b=template.hero.skills.bear,r=b.level;lo=b.damage_min[r-1];max=b.damage_max[r-1];}
        const damage=this.random(lo??h?.minDamage??1,max??h?.damage??3)+(a.buffUntil>this.time?2*(a.courageRank??1):0)+(t?.kind==='barracks'&&t.branch===1?10*t.skills[1]:0);
        a.attackCd=a.transformedUntil&&a.kind==='ingvar'?template.melee.attacks[2].cooldown: a.summon?.interval??(t?(template?.melee?.cooldown??this.stats(t).interval):blockedEnemy?(template?.melee?.cooldown??nativeAttack?.cooldown??h?.interval??1):(nativeAttack?.cooldown??h?.interval??1));a.facing=e.x>=a.x?1:-1;a.anim='attack';a.animUntil=this.time+.4;
        const damageKind:DamageKind=a.summon?.damageKind??(blockedEnemy?(nativeAttack?.damage_type===1?'true':nativeAttack?.damage_type===4?'magic':'physical'):h?.damageKind??'physical');
        if(range>90*REFERENCE_SCALE&&!blockedEnemy)this.fire(a,e,damage,damageKind,{source:a.id,status:a.kind==='elora'?{type:this.rng.next()<.2?'freeze':'slow',remaining:2,power:.5}:undefined,shot:a.kind==='ranger'?'arrow':a.kind==='bolin'?'shotgun':damageKind==='magic'?'magic':'hero'});
        else this.hits.push({effect:'melee',at:this.time+(nativeAttack?.hit_time??.2),target:e.id,point:{...e},damage,kind:damageKind,source:a.id,radius:a.kind==='sasquatch'?80*REFERENCE_SCALE:a.kind==='elemental'?65*REFERENCE_SCALE:a.kind==='tenshi'&&a.transformedUntil?50*REFERENCE_SCALE:undefined,air:false});
        if(a.kind==='ingvar'&&a.transformedUntil)for(const hitTime of template.melee.attacks[2].hit_times.slice(1))this.hits.push({at:this.time+hitTime,target:e.id,point:{...e},damage,kind:'physical',source:a.id});if(a.kind==='bolin'&&!blockedEnemy)for(let j=1;j<3;j++)this.hits.push({at:this.time+j*.4,target:e.id,point:{...e},damage,kind:'physical',source:a.id});
        if(t?.kind==='barracks'&&t.branch===0&&t.skills[2]&&this.rng.next()<.1)this.area(a,50*REFERENCE_SCALE,this.random(25,45)*t.skills[2],'physical',undefined,a.id,false);
        if(t?.kind==='barracks'&&t.branch===1&&t.skills[2]&&this.rng.next()<.1+.05*t.skills[2])this.area(a,40*REFERENCE_SCALE,this.random(10,30)+15*t.skills[2],'physical',undefined,a.id,false);
      }}
      if(t?.kind==='barracks'&&t.branch===0&&t.skills[0]&&a.specialCd<=0&&a.hp<a.maxHp*.7){const amount=this.random(40,60)*t.skills[0];a.hp=Math.min(a.maxHp,a.hp+amount);a.specialCd=10;this.emit('heal',a,{amount});}const regen=template?.regen;if(a.kind==='ingvar'&&a.transformedUntil)a.hp=Math.min(a.maxHp,a.hp+(regen?.health??0)/.5*dt);if(!moving&&!targets.length&&this.time-a.lastHit>(regen?.last_hit_standoff_time??2))a.hp=Math.min(a.maxHp,a.hp+(regen?.health??a.maxHp*.1)/(regen?.cooldown??1)*dt);
      if(t?.kind==='barracks'&&t.branch===1&&t.skills[0]&&a.specialCd<=0){const e=this.targets(a,155*REFERENCE_SCALE,true)[0];if(e){this.fire(a,e,this.random(34,42)+10*(t.skills[0]-1),'physical',{source:a.id,shot:'axe'});a.specialCd=3.5;}}
      if(a.animUntil<=this.time)a.anim=moving?'walk':'idle';
    }
    updateHeroMechanics(this,dt);
  }
  updateEnemies(dt:number){for(const e of [...this.enemies]){if(e.hp<=0)continue;const def=ENEMIES[e.kind];e.attackCd-=dt;e.specialCd-=dt;updateNativeEnemy(this,e,dt);
    for(const s of e.statuses){s.remaining-=dt;if(s.remaining>0&&(s.type==='poison'||s.type==='burn'||s.type==='curse')){if(s.interval){s.next=(s.next??0)-dt;if(s.next<=0){this.damage(e,s.power,s.damageKind??'true',s.source);s.next+=s.interval;}}else this.damage(e,s.power*dt,s.damageKind??'true',s.source);};if(s.remaining>0&&['slow','stun','root','freeze'].includes(s.type)){const slot=this.sourceSlot(s.source);if(slot!==undefined){const m=this.metrics.towers[String(slot)]??={damage:0,overkill:0,control:0,investment:this.towerAt(slot)?.spent??0,blockedSeconds:0,deaths:0};m.control+=dt*(s.type==='slow'?s.power:1);}}}e.statuses=e.statuses.filter(s=>s.remaining>0);if(e.hp<=0)continue;
    const stunned=e.statuses.some(s=>s.type==='stun'||s.type==='freeze')||(e.immobileUntil??0)>this.time,slow=e.statuses.find(s=>s.type==='slow')?.power??0;
    let a=this.blocked.get(e.id);if(a?.hp===0)a=undefined;
    if(def.behavior.ranged&&!a&&!e.sheep)a=this.allies.filter(a=>a.hp>0&&distance(a,e)<def.behavior.ranged!).sort((a,b)=>distance(a,e)-distance(b,e))[0];
    if(stunned){e.moving=false;continue;}
    if(a){e.moving=false;e.blockTime+=dt;if(e.attackCd<=0){e.attackCd=def.interval;e.anim='attack';e.animUntil=this.time+.45;const native=NATIVE[def.native??''],ranged=!!def.behavior.ranged&&!this.blocked.has(e.id),attack=ranged?native?.ranged?.attacks?.[0]:native?.melee?.attacks?.[0],bullet=NATIVE[attack?.bullet]?.bullet,lo=bullet?.damage_min??def.minDamage??def.damage,hi=bullet?.damage_max??def.damage;let incoming=this.random(lo,hi)*((e.rageUntil??0)>this.time?2:1)*((e.damageBuffUntil??0)>this.time?1.2:1);if(ranged)e.attackCd=attack?.cooldown??def.interval;const counter=a.kind==='shield'?heroSnapshot(a).hero.skills.block_counter:undefined;if(counter?.level&&this.rng.next()<heroSnapshot(a).dodge.chance&&!e.sheep){const reflected=incoming*(.5+.5*counter.level);incoming*=incoming>(heroSnapshot(a).dodge?.counter_attack?.damage_threshold??50)?(heroSnapshot(a).dodge?.counter_attack?.damage_factor??.3333333333):0;this.damage(e,reflected,'true',a.id);}nativeEnemyContact(this,e,a,ranged);this.hitAlly(a,e.sheep?0:incoming,attack?.damage_type===1?'true':attack?.damage_type===4?'magic':bullet?.damage_type===8?'explosive':'physical');if(def.behavior.ranged)this.emit('shot',e,{target:{x:a.x,y:a.y},amount:.25,kind:'enemy',color:0xd48977});this.emit('impact',a,{kind:'melee',amount:12});const t=a.tower!==undefined?this.towerAt(a.tower):undefined;if(a.kind==='soldier'&&this.up('barracks',5))this.damage(e,def.damage*.1,'true');
      if(attack?.damage_radius)for(const other of this.allies.filter(f=>f!==a&&f.hp>0&&distance(f,a!)<attack.damage_radius*REFERENCE_SCALE))this.hitAlly(other,this.random(def.minDamage??def.damage,def.damage));if(attack?.damage_type===4096)this.hitAlly(a,99999);
    }}if(!a||(!this.blocked.has(e.id)&&NATIVE[def.native??'']?.ranged?.attacks?.[0]?.hold_advance===false)){e.moving=true;const speed=def.speed*(1-slow)*(e.kind==='boss'&&e.phase===1?1.5:1)*(def.native==='enemy_troll_skater'&&(this.terrain(e)&2048)?NATIVE.mod_troll_skater.speed_factor:1)*((e.flyingUntil??0)>this.time?NATIVE.mod_gulaemon_fly.speed_factor:1);if(e.approach){const d=distance(e,e.approach),step=Math.min(d,speed*dt);if(d>0){e.x+=(e.approach.x-e.x)/d*step;e.y+=(e.approach.y-e.y)/d*step;}if(step>=d-.001)e.approach=undefined;continue;}if(!e.statuses.some(s=>s.type==='root'))e.distance+=speed*dt;for(const portal of this.level.portals??[])if(e.path===portal.path&&e.distance>=portal.from*this.enemyRoad(e).total&&e.distance<portal.to*this.enemyRoad(e).total){e.distance=portal.to*this.enemyRoad(e).total;this.emit('teleport',e);}const next=this.enemyRoad(e).at(e.distance),dx=next.x-e.x,dy=next.y-e.y;e.x=next.x;e.y=next.y;if(Math.abs(dx)+Math.abs(dy)>.01)e.facing=Math.abs(dy)>Math.abs(dx)*1.5?(dy<0?2:0):(dx>=0?1:-1);
      const connection=this.connectedPath(e.path);if(e.distance>=this.goalProgress(e)){if(connection!==undefined){e.path=connection;e.distance=0;Object.assign(e,this.enemyRoad(e).at(0));this.emit('teleport',e);}else{e.hp=0;this.metrics.leaks++;this.lives=Math.max(0,this.lives-def.leak);this.emit('leak',e,{kind:e.kind,amount:def.leak});if(this.lives<=0)this.finish('lost');}}
    }
    const behavior=def.behavior;if(!def.native&&!e.sheep&&behavior.regeneration)e.hp=Math.min(e.maxHp,e.hp+behavior.regeneration*dt);
    if(!def.native&&!e.sheep&&e.specialCd<=0){e.specialCd=behavior.healInterval??behavior.summonInterval??(behavior.boss?12:8);if(behavior.heal)for(const f of this.grid.around(e,behavior.healRange??180).filter(f=>f.hp>0)){f.hp=Math.min(f.maxHp,f.hp+behavior.heal);this.emit('heal',f,{amount:behavior.heal});}if(behavior.summon&&!this.blocked.has(e.id))for(let i=0;i<(behavior.summonCount??3);i++){const n=this.spawn(behavior.summon,e.path,Math.max(0,e.distance-30-i*18));n.bounty=0;}if(behavior.shield)for(const f of this.grid.around(e,220).filter(f=>['demon','hound','imp','demonlord'].includes(f.kind)))f.shieldUntil=this.time+3;if(behavior.aura)for(const f of this.grid.around(e,220)){f.hp=Math.min(f.maxHp,f.hp+30);}
      if(behavior.boss){e.anim='skill';e.animUntil=this.time+1;const summon=behavior.boss==='juggernaut'?'golem':behavior.boss==='winter'?'winterwolf':'demon';for(let i=0;i<3;i++){const n=this.spawn(summon,e.path,Math.max(0,e.distance-i*20));n.bounty=0;}if(behavior.boss==='winter'){for(const t of this.towers.filter(t=>distance(this.level.slots[t.slot],e)<400).slice(0,4)){t.disabledUntil=this.time+15;t.iceClicks=5;this.emit('seal',this.level.slots[t.slot],{text:'冰封：点击五次解除'});}this.addStatus(e,'slow',3,1);}if(behavior.boss==='thorn')for(const t of this.towers.slice(0,Math.min(8,2+Math.max(0,this.wave-9)))){t.sealAt=this.time+3;this.emit('seal',this.level.slots[t.slot],{text:'点击塔解除封印'});}const point=this.allies.find(a=>a.hp>0)??e;this.warnings.push({at:this.time+1.5,point:{...point},kind:'boss',radius:105,damage:150});this.emit('warning',point,{kind:'boss',amount:1.5});}
    }
    if(e.animUntil<=this.time)e.anim=e.moving?'walk':'idle';
  }}
  finish(result:'won'|'lost'){if(this.result!=='playing')return;for(const t of this.towers){const m=this.metrics.towers[String(t.slot)]??={damage:0,overkill:0,control:0,investment:0,blockedSeconds:0,deaths:0};m.investment=Math.max(m.investment,t.spent);}this.result=result;this.emit('result',{x:800,y:450},{kind:result});}
  step(dt=STEP){if(this.result!=='playing')return;this.time+=dt;this.events=this.events.filter(e=>this.time-e.at<2.5);
    this.cooldowns.reinforce=Math.max(0,this.cooldowns.reinforce-dt);this.cooldowns.meteor=Math.max(0,this.cooldowns.meteor-dt);
    while(this.spawns.length&&this.spawns[0].at<=this.time+1e-8){const s=this.spawns.shift()!;const road=this.laneRoads[s.path]?.[s.subPath??0]??this.roads[s.path],e=this.spawn(s.kind,s.path,s.progress??road.lengths[s.node??this.level.pathStarts?.[s.path]??0]??0,false,s.subPath??0);if(s.bounty!==undefined)e.bounty=s.bounty;if(s.hp!==undefined)e.hp=Math.min(e.maxHp,s.hp);e.generation=s.generation??0;if(s.from){Object.assign(e,s.from);e.approach=s.forcedWaypoint??road.at(e.distance);const birth=this.events.at(-1);if(birth?.type==='spawn')birth.point={...s.from};}}
    // Auto progress is based on clear state, never on the nominal reward clock.
    this.grid.rebuild(this.enemies.filter(e=>e.hp>0));
    const ready=this.hits.filter(h=>h.at<=this.time);this.hits=this.hits.filter(h=>h.at>this.time);
    for(const h of ready){const target=h.target!==undefined?this.enemies.find(e=>e.id===h.target&&e.hp>0):undefined;const p=target??h.point;if(h.radius)this.area(p,h.radius,h.damage,h.kind,h.status,h.source,h.air);else if(target){this.damage(target,h.damage,h.kind,h.source);if(h.status&&target.hp>0)this.addStatus(target,h.status.type,h.status.remaining,h.status.power,h.source);this.emit('impact',p,{targetId:target.id,effect:h.effect,kind:h.kind,damageKind:h.kind,color:h.kind==='magic'?0x83dfff:0xffdf91,amount:16,...this.effectDetails(h.source)});}}
    const warnings=this.warnings.filter(w=>w.at<=this.time);this.warnings=this.warnings.filter(w=>w.at>this.time);
    for(const w of warnings){if(w.kind==='meteor'){this.area(w.point,w.radius,w.damage,'true',undefined,undefined,false);if(this.up('meteor',2))this.zones.push({point:w.point,until:this.time+(this.up('meteor',4)?10:5),next:this.time+1});}else{for(const a of this.allies.filter(a=>a.hp>0&&distance(a,w.point)<w.radius))this.hitAlly(a,w.damage);this.emit('impact',w.point,{kind:'boss',color:0xff784a,amount:w.radius,radius:w.radius});}}
    for(const zone of this.zones)if(this.time>=zone.next&&this.time<zone.until){zone.next=this.time+1;this.area(zone.point,65*REFERENCE_SCALE,this.random(10,20),'physical',undefined,undefined,false);}this.zones=this.zones.filter(z=>z.until>this.time);this.updateAllies(dt);updateNativeFacilities(this,dt);this.updateTowers(dt);this.updateEnemies(dt);this.updateFacilities();
    this.enemies=this.enemies.filter(e=>e.hp>0);this.updateAutoWave();this.allies=this.allies.filter(a=>!!a.facility||!a.expires||a.expires>this.time&&a.hp>0);
    if(this.result==='playing'&&this.wave===this.level.waves.length&&this.time+1e-8>=this.waveCompleteAt&&!this.enemies.length&&!this.spawns.length){if(this.level.id==='stage-12'&&this.level.mode!=='iron'&&this.level.mode!=='heroic'&&!this.finalBossStarted){this.finalBossStarted=true;const p={x:200+518*REFERENCE_SCALE,y:900-677*REFERENCE_SCALE};this.spawn('boss',0,this.roads[0].nearest(p).progress);}else this.finish('won');}
  }
  advanced(t:TowerState,p:Point,stats:ReturnType<Simulation['stats']>){const list=this.targets(p,stats.range,true),e=list[0];if(!e)return;const a=t.skills[0],b=t.skills[1];
    if(t.skillCd<=0&&a){t.skillCd=14;if(t.kind==='archer'&&t.branch===1){if(!ENEMIES[e.kind].behavior.boss&&this.rng.next()<a*.2&&this.canAffect(e,'instakill')){this.recordExecution(e,t.slot);e.hp=0;this.kill(e);}else this.fire(p,e,e.maxHp*a*.2,'physical',{shot:'sniper',source:-100-t.slot});}
      if(t.kind==='mage'&&t.branch===0){t.skillCd=22-a*2;if(this.canAffect(e,'disintegrate')){this.recordExecution(e,t.slot);e.hp=0;this.kill(e);this.emit('skill',e,{kind:'deathray',target: {...p},...this.effectDetails(-100-t.slot)});}}
      if(t.kind==='mage'&&t.branch===1){t.skillCd=22-a*2;if(this.canAffect(e,'polymorph')&&!e.sheep){e.sheep=true;e.armor=0;e.hp*=.5;e.maxHp=e.hp;e.statuses=[];this.emit('skill',e,{kind:'polymorph',...this.effectDetails(-100-t.slot)});}}
      if(t.kind==='engineer'&&t.branch===0){const target=this.targets(p,180*(1+.2*a)*REFERENCE_SCALE,true)[0];if(target){t.skillCd=this.isFlying(target)?6.5:14.1;this.fire(p,target,this.random(100+40*(a-1),140+40*(a-1)),'explosive',{radius:41.25*REFERENCE_SCALE,air:true,shot:'missile',source:-100-t.slot});}}
    }
    if(t.secondaryCd<=0&&b){t.secondaryCd=10;
      if(t.kind==='archer'&&t.branch===0){t.secondaryCd=NATIVE.aura_ranger_thorn.aura.cooldown;for(const f of this.targets(p,200*REFERENCE_SCALE,false).filter(f=>this.canAffect(f,'thorn')&&f.roots<3).slice(0,2+b*2)){f.roots++;this.addStatus(f,'root',b,1,-100-t.slot);this.addStatus(f,'burn',b+.001,40,-100-t.slot,{damageKind:'physical',interval:1,next:1});this.emit('skill',f,{kind:'roots',source:-100-t.slot,radius:24});}}
      if(t.kind==='archer'&&t.branch===1){t.secondaryCd=9;const target=this.targets(p,117.5*REFERENCE_SCALE,false)[0];if(target)for(let i=0;i<6;i++)this.fire(p,target,this.random(10,40)*b,'explosive',{radius:48*REFERENCE_SCALE,air:false,shot:'shrapnel',source:-100-t.slot});}
      if(t.kind==='mage'&&t.branch===0)for(const f of this.targets(e,32.5*REFERENCE_SCALE,true).filter(f=>this.canAffect(f,'teleport')&&f.teleports<3&&f.distance>(this.enemyRoad(f).lengths[15]??0)).slice(0,3+b)){f.teleports++;f.distance=Math.max(0,f.distance-this.random(17+5*b,26+5*b)*5*REFERENCE_SCALE);Object.assign(f,this.enemyRoad(f).at(f.distance));this.emit('teleport',f);}
      if(t.kind==='engineer'&&t.branch===0){t.secondaryCd=17;for(let i=0;i<1+2*b;i++){const point={x:e.x+this.random(-90,90),y:e.y+this.random(-70,70)};this.hits.push({at:this.time+.5+i*.1,point,damage:this.random(60,80),kind:'explosive',radius:52.5*REFERENCE_SCALE,air:false,source:-100-t.slot});this.emit('shot',p,{kind:'missile',effect:'missile',target:point,amount:.5+i*.1,radius:52.5*REFERENCE_SCALE,damageKind:'explosive',...this.effectDetails(-100-t.slot)});}}
      
    }
  }
  facility(id:string,point?:Point){const f=this.level.facilities?.find(f=>f.id===id),state=this.facilityStates.get(id);if(!f||!state)return false;if(f.kind==='sunray'&&point){if(!state.rank||state.next>this.time){this.lastError='先招募术士，或等待阳光冷却';return false;}const target=this.targets(point,65*REFERENCE_SCALE,true)[0];if(!target){this.lastError='请选择阳光射线范围内的敌人';return false;}this.damage(target,this.random(25,75)+50*state.rank,'true');this.emit('shot',f,{target:{...target},kind:'sunray',effect:'magic',damageKind:'true',amount:.1});state.next=this.time+22-state.rank*3;return true;}if(!['elves','sasquatch','sunray'].includes(f.kind))return false;if(f.kind==='sasquatch'&&!state.thawed){this.lastError='先用流星融化冰洞';return false;}if(state.rank>=(f.kind==='sasquatch'?1:4)||this.gold<(f.cost??100)){this.lastError='金币不足或招募已满';return false;}this.gold-=f.cost??100;state.rank++;if(f.kind!=='sunray'){const a=this.createSoldier(undefined,state.rank,{x:f.x,y:f.y});a.kind=f.kind==='sasquatch'?'sasquatch':'elf';a.facility=f.id;a.maxHp=a.hp=(a.kind==='sasquatch'?2500:100)*(this.difficulty==='casual'?1.2:1);a.armor=0;a.expires=Infinity;this.route(a,this.roads[f.path].at(f.progress*this.roads[f.path].total));}else state.next=this.time;this.emit('upgrade',f,{text:'招募成功'});return true;}
  updateAutoWave(){
    if(this.waveTiming==='original'){this.autoWaveAt=Infinity;if(this.autoWave&&this.wave>0&&this.time+1e-8>=this.nextWaveAt)this.startWave();return;}
    const clear=this.wave>0&&this.time+1e-8>=this.waveCompleteAt&&!this.enemies.some(e=>e.hp>0)&&!this.spawns.length;
    if(!clear){this.autoWaveAt=Infinity;return;}
    this.waveActive=false;
    if(this.wave>=this.level.waves.length||!this.autoWave){this.autoWaveAt=Infinity;return;}
    if(!Number.isFinite(this.autoWaveAt))this.autoWaveAt=this.time+3;
    if(this.time+1e-8>=this.autoWaveAt)this.startWave();
  }
  waveStatus(){return this.wave===0?'准备第一波':this.spawns.length?'本波进攻中':this.enemies.some(e=>e.hp>0)?'仍有敌人':this.wave>=this.level.waves.length?'最终清场':!this.autoWave?'等待手动开波':'下一波：'+(Number.isFinite(this.autoWaveAt)?Math.max(0,Math.ceil(this.autoWaveAt-this.time)):3)+'秒';}
  sourceSlot(source?:number){return source===undefined?undefined:source<0?-100-source:this.allies.find(a=>a.id===source)?.tower;}
  effectDetails(source?:number){const t=source!==undefined&&source<0?this.towerAt(-100-source):this.towerAt(this.allies.find(a=>a.id===source)?.tower??-1);return{source,towerKind:t?.kind,towerLevel:t?.level??1,branch:t?.branch??-1};}
  updateFacilities(){for(const f of this.level.facilities??[]){const state=this.facilityStates.get(f.id)!;if(!['summon','magma'].includes(f.kind)||this.wave<(f.activeFromWave??1)||this.time<state.next||this.wave===0||!this.waveActive)continue;state.next=this.time+(f.every??60);const e=this.spawn(f.kind==='magma'?'magma':'demon',f.path,this.roads[f.path].total*f.progress);if(f.kind==='summon')e.bounty=0;}}

}

