export type Point = { x:number; y:number };
export type TowerKind = 'archer'|'barracks'|'mage'|'engineer';
export type HeroKind = 'shield'|'ranger'|'malik'|'bolin'|'star'|'ignus'|'healer'|'elora'|'ingvar'|'hacksaw'|'oni'|'thor'|'tenshi';
export type EnemyKind = string;
export type DamageKind = 'physical'|'magic'|'true'|'explosive';
export type Difficulty = 'casual'|'normal'|'veteran'|'challenge';
export type GameMode = 'campaign'|'heroic'|'iron';
export type SkillKind = 'reinforce'|'meteor';
export type AnimationName = 'idle'|'walk'|'attack'|'hurt'|'skill'|'death';
export interface AbilityDefinition { id:string; name:string; description:string; cost:number; costs:number[]; maxLevel:number }
export interface TowerBranch { name:string; description:string; cost:number; damage:number; minDamage:number; range:number; interval:number; skills:AbilityDefinition[] }
export interface TowerDefinition { id:TowerKind; name:string; description:string; row:number; costs:number[]; damage:number[]; minDamage:number[]; range:number[]; interval:number[]; damageKind:DamageKind; air:boolean; branches:TowerBranch[] }
export interface HeroDefinition { reference?:string;unlockLevel?:number;native?:string;levelStats?:{hp:number;armor:number;minDamage:number;maxDamage:number;regen:number}[];teleport?:boolean;minDamage?:number; id:HeroKind; name:string; role:string; description:string; row:number; hp:number; damage:number; range:number; speed:number; interval:number; armor:number; damageKind:DamageKind; air:boolean; block:number; revive:number; skills:[string,string] }
export interface EnemyBehavior { native?:string;deathSpawn?:string;deathSpawnCount?:number;reviveAs?:string;transformAt?:number;transformInto?:string;dodge?:number;summonGeneration?:number;areaRadius?:number;damageKind?:DamageKind;bossId?:string; regeneration?:number; heal?:number; healRange?:number; healInterval?:number; ranged?:number; summon?:string; summonCount?:number; summonInterval?:number; split?:string; explode?:number; shield?:boolean; aura?:boolean; boss?:'juggernaut'|'winter'|'thorn'|'expansion'; poisonImmune?:boolean; controlImmune?:boolean }
export interface EnemyDefinition { minDamage?:number;native?:string;difficultyHp?:number[]; id:EnemyKind; name:string; description:string; reference?:string; sheet:string; row:number; hp:number; speed:number; damage:number; interval:number; armor:number; resist:number; gold:number; leak:number; flying?:boolean; size:number; behavior:EnemyBehavior; rig?:'biped'|'quadruped'|'spider'|'flying'|'blob'; tint?:number }
export interface SpawnGroup { type:EnemyKind; count:number; path:number; interval:number; delay:number }
export interface SpawnTimelineEntry { tick:number;type:EnemyKind;path:number;subPath:number;node?:number;from?:Point;forcedWaypoint?:Point }
export interface WaveDefinition { groups:SpawnGroup[]; rest:number; purpose?:string;timeline?:SpawnTimelineEntry[];timelines?:Record<string,SpawnTimelineEntry[]>;completeTick?:number;completeTicks?:Record<string,number>;extraTimelines?:Record<string,SpawnTimelineEntry[]>;originalInterval?:number;native?:unknown }
export interface Rect extends Point { width:number; height:number }
export interface PortalDefinition { path:number; from:number; to:number }
export type FacilityKind = 'elves'|'sasquatch'|'sunray'|'graveyard'|'summon'|'magma'|'guards';
export interface FacilityDefinition extends Point { id:string; kind:FacilityKind; path:number; progress:number; cost?:number; every?:number; activeFromWave?:number }
export interface ModeDefinition { lives:number; gold:number; waves:WaveDefinition[]; maxTowerLevel:number; maxUpgrade:number; heroes:boolean; allowedTowers:TowerKind[] }
export interface PrebuiltTower { slot:number; kind:TowerKind; level:number; branch?:number }
export interface LevelDefinition { pathStarts?:number[];pathEnds?:number[];exitPoints?:Point[]; version:1|2|3;logicalSize?:{width:number;height:number;scale:number;offsetX:number};subPaths?:Point[][][];pathConnections?:unknown;densePaths?:boolean;walkingGrid?:{ox:number;oy:number;grid:number[][]};defaultRallies?:Point[];chapterId?:string;requires?:string[];scriptEvents?:{template:string;point?:Point;data?:Record<string,unknown>}[];lockedPowers?:boolean[];referenceBuild?:number; id:string; name:string; subtitle:string; description:string; map:string; gold:number; paths:Point[][]; slots:Point[]; heroStart:Point; waves:WaveDefinition[]; recommended:string; duration:string; reference?:string; chapter?:number; maxTowerLevel?:number; unlocks?:Partial<Record<TowerKind,number>>; unlockAtWave?:Partial<Record<TowerKind,number>>; obstacles?:Rect[]; portals?:PortalDefinition[]; facilities?:FacilityDefinition[]; modes?:Partial<Record<GameMode,ModeDefinition>>;prebuilt?:PrebuiltTower[]; lives?:number; maxUpgrade?:number; heroes?:boolean; allowedTowers?:TowerKind[]; node?:Point; mode?:GameMode; scouting?:{majorEnemies:string[]};tutorial?:{lesson:number} }
export interface CampaignDefinition { version:2; id:string; name:string; description:string; ordered:boolean; levels:LevelDefinition[]; updatedAt:number }
export type PlayerCommand = {type:'build';slot:number;kind:TowerKind}|{type:'upgrade';slot:number;branch?:number}|{type:'sell';slot:number}|{type:'tower-skill';slot:number;skill:number}|{type:'rally';slot:number;point:Point}|{type:'move-hero';point:Point;append?:boolean}|{type:'cast';skill:SkillKind;point:Point}|{type:'next-wave'}|{type:'auto-wave';enabled:boolean}|{type:'unseal';slot:number}|{type:'facility';id:string;point?:Point}|{type:'pop-sheep';id:number};
export interface Status { type:'slow'|'stun'|'poison'|'burn'|'mark'|'root'|'freeze'|'curse'; remaining:number; power:number; source?:number; damageKind?:DamageKind; interval?:number; next?:number }
export interface EnemyState extends Point { approach?:Point;shieldHits?:number;damageBuffUntil?:number;spectralBuffed?:boolean;immobileUntil?:number; nativeCds?:Record<string,number>;flyingUntil?:number;rageUntil?:number; id:number; kind:EnemyKind; hp:number; maxHp:number; path:number;subPath?:number;generation?:number;revived?:boolean; distance:number; attackCd:number; specialCd:number; statuses:Status[]; lastHit:number; moving:boolean; facing:number; anim:AnimationName; animUntil:number; phase:number; blockTime:number; armor:number; bounty:number; teleports:number; roots:number; sheep:boolean; deathPaid:boolean; shieldUntil:number }
export interface AllyState extends Point {charge?:{until:number;damage:number;hitIds:number[]};infectedAs?:string; stunnedUntil?:number;courageRank?:number;dot?:{until:number;next:number;power:number;interval:number;nonlethal:boolean}; summon?:{template:string;damage:number;minDamage:number;speed:number;range:number;interval:number;damageKind:DamageKind};transformedUntil?:number;heroCds?:Record<string,number>;immuneUntil?:number; targetId?:number;id:number; kind:'soldier'|'elemental'|'elf'|'sasquatch'|'pet'|'illusion'|'ancestor'|HeroKind; tower?:number; facility?:string; hp:number; maxHp:number; destination:Point; waypoints:Point[]; anchor:Point; commanded:boolean; attackCd:number; specialCd:number; secondaryCd:number; lastHit:number; revive:number; expires?:number; armor:number; moving:boolean; facing:number; anim:AnimationName; animUntil:number; level:number; xp:number; buffUntil:number; walkDistance:number }
export interface TowerState { sealClicks?:number; buffUntil?:number; slot:number;kind:TowerKind;level:number;branch:number;spent:number;attackCd:number;skillCd:number;secondaryCd:number;skills:number[];rally:Point;disabledUntil:number;sealAt:number;iceClicks?:number;firedAt:number }
export interface CombatEvent { id:number;type:'shot'|'impact'|'death'|'heal'|'skill'|'upgrade'|'spawn'|'warning'|'wave'|'leak'|'result'|'teleport'|'seal';at:number;point:Point;target?:Point;color?:number;damageKind?:DamageKind;kind?:string;phase?:number;actor?:number;slot?:number;morphed?:boolean;text?:string;amount?:number;source?:number;targetId?:number;towerKind?:TowerKind;towerLevel?:number;branch?:number;radius?:number;effect?:string }
export interface AtlasFrame { frame:Rect; sourceSize:{w:number;h:number}; anchor:Point; action?:string }
export interface AssetManifest {version:number;maps:string[];atlases:Record<string,{file:string;columns:number;rows:number}>;sources:string[]}
export interface Score { stars:number;lives:number;hero:HeroKind;difficulty:Difficulty }
export interface SaveData { version:4;rulesVersion?:number;scores:Record<string,Score>;hero:HeroKind;upgrades:Record<string,number>;discovered:string[];training:{completed:string[];dismissed:boolean;steps?:Record<string,number>};legacy?:{scores:Record<string,Score>;upgrades:Record<string,number>};settings:{sound:boolean;music:boolean;lowQuality:boolean;autoWave:boolean;speed:1|2|3;waveTiming?:'clear'|'original';masterVolume:number;musicVolume:number;sfxVolume:number;ambientVolume:number} }
export interface UpgradeNode {name:string;description:string;cost:number}

